#![allow(dead_code)]
// This file is automatically generated. DO NOT MAKE EDITS HERE!
// To make changes, see ../vocab/autogen-hsk.rb

// Longest homophone choice size (choices joined by "\t")
pub const CIYU_CHOICE_MAX: usize = 5;

pub static CIYU: &[&'static str] = &[
    &"日记",
    &"香蕉",
    &"直接",
    &"兴趣",
    &"菜	才	猜",
    &"对",
    &"性别",
    &"钱	前	千",
    &"数字",
    &"糖	躺	汤	趟",
    &"分钟",
    &"举办",
    &"好处",
    &"接着",
    &"乘坐",
    &"放心",
    &"办事",
    &"地球",
    &"坏",
    &"变	遍",
    &"年",
    &"距离",
    &"厉害",
    &"公共汽车",
    &"拒绝",
    &"厨房",
    &"身体",
    &"超市",
    &"出现",
    &"最	嘴",
    &"专门",
    &"春游",
    &"烦恼",
    &"科学",
    &"茶	差",
    &"稍微",
    &"美丽",
    &"力气",
    &"几乎",
    &"丰富",
    &"完成",
    &"不客气",
    &"结束",
    &"没	每	美",
    &"粗心",
    &"加油站",
    &"历史",
    &"奇怪",
    &"感到",
    &"科技",
    &"甚至",
    &"盘子",
    &"中午",
    &"爱好",
    &"开玩笑",
    &"来自",
    &"舞蹈",
    &"地点",
    &"难受",
    &"引起",
    &"层",
    &"饺子",
    &"重视",
    &"错",
    &"积累",
    &"研究",
    &"欢迎",
    &"旁边",
    &"海洋",
    &"无聊",
    &"脱",
    &"他	她	它",
    &"安排",
    &"汉语",
    &"小雨",
    &"有趣",
    &"喂	为	位",
    &"怎么",
    &"尊重",
    &"弟弟",
    &"中间",
    &"吃",
    &"空调",
    &"爱	矮",
    &"缺点",
    &"牙膏",
    &"中文",
    &"有限",
    &"告诉",
    &"老虎",
    &"打扰",
    &"需要",
    &"只要",
    &"钱包",
    &"有点儿",
    &"这些",
    &"难过",
    &"竞争",
    &"帅",
    &"发烧",
    &"垃圾",
    &"马虎",
    &"商店",
    &"少	勺",
    &"合适",
    &"报名",
    &"导游",
    &"感觉",
    &"聊天儿",
    &"穷",
    &"标准",
    &"天	甜	填",
    &"总结",
    &"主要",
    &"质量",
    &"照相机",
    &"一下",
    &"橡皮",
    &"一会儿",
    &"三	伞",
    &"老师",
    &"干净",
    &"黄",
    &"注意	主意",
    &"生活",
    &"女孩儿",
    &"衬衫",
    &"京剧",
    &"作业",
    &"一	以",
    &"毛巾",
    &"流利",
    &"裙子",
    &"吗	马",
    &"冷",
    &"到底",
    &"香山",
    &"要是	钥匙",
    &"口",
    &"拉	辣",
    &"踢足球",
    &"带	戴	袋",
    &"你们",
    &"语言",
    &"楼",
    &"得意",
    &"继续",
    &"人名",
    &"叔叔",
    &"然后",
    &"原因",
    &"汗",
    &"面试",
    &"能力",
    &"可能",
    &"新	信",
    &"究竟",
    &"只好",
    &"相信",
    &"后	厚",
    &"杯子",
    &"律师",
    &"休息",
    &"积极",
    &"加油",
    &"浪漫",
    &"认为",
    &"紧张",
    &"桌子",
    &"情况",
    &"北京",
    &"旅行",
    &"适合",
    &"翻译",
    &"丈夫",
    &"讨论",
    &"大使馆",
    &"粉色",
    &"路",
    &"鼻子",
    &"年龄",
    &"污染",
    &"喝	和	河",
    &"有意思",
    &"忘记",
    &"警察",
    &"行李箱",
    &"月	越	约",
    &"孩子",
    &"大夫",
    &"减轻",
    &"啊",
    &"找	照",
    &"妹妹",
    &"不得不",
    &"介绍",
    &"女",
    &"更",
    &"尤其",
    &"危险",
    &"记者",
    &"计划",
    &"秒",
    &"双",
    &"意思",
    &"哥哥",
    &"公里",
    &"并且",
    &"所以",
    &"减少",
    &"看法",
    &"重要",
    &"按照",
    &"生病",
    &"叶子",
    &"爸爸",
    &"其实",
    &"阳光",
    &"矿泉水",
    &"新鲜",
    &"洗手间",
    &"下面",
    &"掉",
    &"件	减",
    &"医生",
    &"生命",
    &"小时",
    &"顾客",
    &"水平",
    &"表演",
    &"筷子",
    &"职业",
    &"关心",
    &"幸福",
    &"笔记本",
    &"上网",
    &"不错",
    &"谢谢",
    &"信心",
    &"一样",
    &"空",
    &"感情",
    &"交通",
    &"男	南	难",
    &"酸",
    &"漂亮",
    &"信息",
    &"黑板",
    &"铅笔",
    &"合格",
    &"米饭",
    &"沙发",
    &"腿	推",
    &"条",
    &"哪里",
    &"关于",
    &"新年",
    &"选择",
    &"雨	鱼	与",
    &"方法",
    &"过去",
    &"达到",
    &"街道",
    &"听说",
    &"声音",
    &"亚洲",
    &"可怜",
    &"深",
    &"等	灯",
    &"校园",
    &"存",
    &"经过",
    &"一定",
    &"爷爷",
    &"没有",
    &"根据",
    &"赶	敢	干",
    &"云",
    &"生意",
    &"严格",
    &"请	晴	轻",
    &"全部",
    &"谁",
    &"保护",
    &"知识",
    &"排队",
    &"鼓励",
    &"读	度	堵",
    &"疼",
    &"结果",
    &"邀请",
    &"哭	苦",
    &"大	打",
    &"被	倍",
    &"进行",
    &"再见",
    &"理解",
    &"怎么样",
    &"春",
    &"看",
    &"出租车",
    &"牙刷",
    &"毕业",
    &"打针",
    &"起来",
    &"餐",
    &"正在",
    &"给",
    &"秋",
    &"得到",
    &"胖",
    &"区别",
    &"下雨",
    &"六一儿童节",
    &"普通",
    &"迷路",
    &"习惯",
    &"数量",
    &"共同",
    &"房间",
    &"远	元",
    &"心情",
    &"应聘",
    &"难道",
    &"也	页",
    &"风景",
    &"其中",
    &"精神",
    &"将来",
    &"学习",
    &"购物",
    &"觉得",
    &"妈妈",
    &"竟然",
    &"空儿",
    &"座位",
    &"飞机",
    &"北方",
    &"全",
    &"报纸",
    &"长期",
    &"词语",
    &"巧克力",
    &"明天",
    &"车",
    &"日",
    &"性格",
    &"小朋友",
    &"厕所",
    &"闹钟",
    &"奶奶",
    &"散步",
    &"牛奶",
    &"比赛",
    &"客人",
    &"密码",
    &"葡萄",
    &"西红柿",
    &"眼睛	眼镜",
    &"回答",
    &"面条",
    &"经济",
    &"不仅",
    &"做客",
    &"当",
    &"很",
    &"超过",
    &"首都机场",
    &"菜单",
    &"题	提",
    &"教室",
    &"颜色",
    &"会议	回忆",
    &"味道",
    &"改变",
    &"真",
    &"图书馆",
    &"学生",
    &"香瓜",
    &"米",
    &"二	而",
    &"方面",
    &"于是",
    &"吃饭",
    &"受不了",
    &"什么",
    &"熊猫",
    &"镜子",
    &"从",
    &"下午",
    &"花花",
    &"小心",
    &"知道",
    &"高兴",
    &"清楚",
    &"个	各",
    &"放暑假",
    &"女性",
    &"粉	分	份",
    &"符合",
    &"胳膊",
    &"睡觉",
    &"还是",
    &"购买",
    &"刚才",
    &"来得及",
    &"准时",
    &"照顾",
    &"纸袋",
    &"文化",
    &"友好",
    &"互联网",
    &"事情",
    &"对面",
    &"叫	教	角	脚	交",
    &"熟悉",
    &"星期",
    &"句	举",
    &"责任",
    &"健康",
    &"登机牌",
    &"技术",
    &"收入",
    &"地方",
    &"改",
    &"课	渴	刻	可	棵",
    &"景色",
    &"生气",
    &"为了",
    &"基础",
    &"安全",
    &"可是",
    &"垃圾桶",
    &"睡着",
    &"美人鱼",
    &"打扮",
    &"节约",
    &"增",
    &"里	李	离	丽",
    &"出发",
    &"敲	桥",
    &"窗",
    &"有名",
    &"通过",
    &"哪	那	拿",
    &"讨厌",
    &"明",
    &"必须",
    &"凉茶",
    &"批评",
    &"迟到",
    &"商场",
    &"空气",
    &"新闻",
    &"公斤",
    &"水",
    &"留学",
    &"母亲",
    &"表格",
    &"长江",
    &"面包",
    &"同意",
    &"已经",
    &"中秋节",
    &"恐怕",
    &"都",
    &"仔细",
    &"六	留",
    &"机场",
    &"刮风",
    &"意见",
    &"内",
    &"演出",
    &"玩儿",
    &"专业",
    &"果汁",
    &"小	笑",
    &"过程",
    &"满意",
    &"昨天",
    &"讲	奖",
    &"降落",
    &"无论",
    &"来",
    &"便宜",
    &"小伙子",
    &"复习",
    &"来不及",
    &"盒子",
    &"地铁",
    &"精彩",
    &"比如",
    &"作者",
    &"多",
    &"办法",
    &"时候",
    &"感兴趣",
    &"去	取",
    &"打折",
    &"样子",
    &"森林",
    &"同样",
    &"挂",
    &"邮局",
    &"轻松",
    &"电子邮件",
    &"永远",
    &"一共",
    &"比较",
    &"先	咸",
    &"忙",
    &"小区",
    &"有关",
    &"愿意",
    &"亲戚",
    &"凉快",
    &"非常",
    &"提高",
    &"兴奋",
    &"白	百",
    &"出差",
    &"可爱",
    &"音乐",
    &"脏",
    &"袜子",
    &"预习",
    &"八	吧	把",
    &"还	海",
    &"人	认",
    &"赚	转",
    &"体育馆",
    &"饼干",
    &"保证",
    &"会员卡",
    &"红",
    &"方向",
    &"原谅",
    &"努力",
    &"变化",
    &"考虑",
    &"成绩",
    &"聊天",
    &"以前",
    &"中国",
    &"高速公路",
    &"一切",
    &"妻子",
    &"举行",
    &"咱们",
    &"红色",
    &"制冷",
    &"成",
    &"跑步",
    &"猫	毛",
    &"效果",
    &"重点",
    &"正好",
    &"如果",
    &"热情",
    &"只	指	之	纸",
    &"植物",
    &"阿姨",
    &"正式",
    &"而且",
    &"离开",
    &"前面",
    &"能",
    &"反对",
    &"申请",
    &"擦",
    &"工资",
    &"椅子",
    &"小说",
    &"吵",
    &"帮助",
    &"部分",
    &"至少",
    &"按时",
    &"盐",
    &"十	是	试	使",
    &"其他",
    &"些	写	谢",
    &"今天",
    &"请假",
    &"售货员",
    &"调查",
    &"自然",
    &"让",
    &"流血",
    &"实在",
    &"送",
    &"肯定",
    &"塑料袋",
    &"安娜",
    &"应该",
    &"但是",
    &"材料",
    &"这	着	折",
    &"一起",
    &"愉快",
    &"冷静",
    &"照片",
    &"旅游",
    &"互相",
    &"杂志",
    &"公司",
    &"演员",
    &"免费",
    &"不同",
    &"姐姐",
    &"活动",
    &"陪",
    &"练习	联系",
    &"抓",
    &"想	向	像	香	响",
    &"仍然",
    &"暂时",
    &"高",
    &"获得",
    &"可惜",
    &"气候",
    &"坐	做	座",
    &"遇到",
    &"结婚",
    &"广播",
    &"世界",
    &"决定",
    &"走",
    &"航班",
    &"机会",
    &"差不多",
    &"广告",
    &"时间",
    &"家具",
    &"比",
    &"每天",
    &"红酒",
    &"别",
    &"花	画",
    &"饿",
    &"填空",
    &"大约",
    &"饮料",
    &"接	借	节	街",
    &"用",
    &"同情",
    &"吸引",
    &"态度",
    &"杨	养",
    &"大家",
    &"好像",
    &"懂	东	冬",
    &"国	过",
    &"消息",
    &"地图",
    &"却",
    &"关",
    &"并",
    &"百分之",
    &"严重",
    &"师傅",
    &"梦",
    &"影响",
    &"堵车",
    &"传真",
    &"短	段",
    &"或者",
    &"开心",
    &"见面",
    &"啤酒",
    &"运动",
    &"耐心",
    &"养成",
    &"父母",
    &"其次",
    &"困难",
    &"害羞",
    &"打印",
    &"减肥",
    &"火	货",
    &"热",
    &"省	剩",
    &"随着",
    &"刚",
    &"西瓜",
    &"缺少",
    &"袋子",
    &"成功",
    &"羊肉",
    &"邻居",
    &"受到",
    &"阴",
    &"终于",
    &"咳嗽",
    &"笔试",
    &"教育",
    &"山",
    &"头发",
    &"一般",
    &"出生",
    &"首先",
    &"锻炼",
    &"感冒",
    &"左边",
    &"帮忙",
    &"汉字",
    &"美国",
    &"千万",
    &"零钱",
    &"有效",
    &"签证",
    &"硕士",
    &"重新",
    &"数学",
    &"到时候",
    &"许多",
    &"自信",
    &"电视",
    &"活泼",
    &"记得",
    &"累",
    &"破",
    &"扔",
    &"艺术",
    &"表",
    &"一点儿",
    &"同学",
    &"问",
    &"东西",
    &"服务员",
    &"脸	连",
    &"帮	棒",
    &"包子",
    &"张	长",
    &"零	另",
    &"太	台	抬",
    &"票",
    &"生日",
    &"往往",
    &"蓝	懒",
    &"慢	满",
    &"从来",
    &"早上",
    &"蛋糕",
    &"呢",
    &"当时",
    &"面对",
    &"办公室",
    &"动作",
    &"新鲜感",
    &"水果",
    &"进	近",
    &"准备",
    &"增加",
    &"笑话",
    &"支持",
    &"小姐",
    &"出	处",
    &"误会",
    &"使用",
    &"价格",
    &"后来",
    &"值得",
    &"事半功倍",
    &"穿	船",
    &"打篮球",
    &"规定",
    &"笔记",
    &"音乐会",
    &"回	会",
    &"目的",
    &"耳朵",
    &"唱歌",
    &"赢",
    &"观众",
    &"普通话",
    &"月亮",
    &"功夫",
    &"年轻",
    &"广东省",
    &"速度",
    &"方	放",
    &"不过",
    &"复印",
    &"贵",
    &"也许",
    &"太阳",
    &"家	假	加",
    &"一般来说",
    &"爬山",
    &"骄傲",
    &"礼物",
    &"提供",
    &"暖",
    &"建议",
    &"经常",
    &"排列",
    &"聪明",
    &"上海",
    &"顺序",
    &"瓶子",
    &"光	逛",
    &"王	往",
    &"路口",
    &"地址",
    &"加班",
    &"不但",
    &"修理",
    &"教授",
    &"天气",
    &"放松",
    &"只有",
    &"打电话",
    &"故意",
    &"对话",
    &"同事	同时",
    &"偶尔",
    &"关键",
    &"民族",
    &"否则",
    &"卫生间",
    &"得",
    &"怪",
    &"皮鞋",
    &"我",
    &"药	要",
    &"护照",
    &"价钱",
    &"大卫",
    &"国家",
    &"房子",
    &"节日",
    &"接受",
    &"电梯",
    &"长城",
    &"第一",
    &"笑笑",
    &"错误",
    &"现在",
    &"网站",
    &"静",
    &"信用卡",
    &"详细",
    &"手	瘦	收	受",
    &"乱",
    &"对于",
    &"咱",
    &"文章",
    &"安静",
    &"租",
    &"校长",
    &"勇敢",
    &"体育",
    &"坚持",
    &"着急",
    &"作用",
    &"晚上",
    &"到	刀	倒",
    &"点",
    &"买	卖",
    &"孙月",
    &"电脑",
    &"了",
    &"九	就	久	旧	酒",
    &"手机",
    &"真正",
    &"准确",
    &"完	玩	碗	万",
    &"左右",
    &"多少",
    &"外地",
    &"解释",
    &"提醒",
    &"狗	够	购",
    &"热闹",
    &"喜欢",
    &"突然",
    &"女儿",
    &"温度",
    &"首都",
    &"还	换",
    &"负责",
    &"长江大桥",
    &"有	又	由",
    &"及时	即使",
    &"跳舞",
    &"环境",
    &"动物",
    &"窗户",
    &"鲜花",
    &"不	部",
    &"银行",
    &"饭店",
    &"困",
    &"周末",
    &"最好",
    &"林",
    &"可乐",
    &"不管",
    &"老",
    &"奖金",
    &"经理	经历",
    &"例如",
    &"节目",
    &"感谢",
    &"伤心",
    &"不少",
    &"房东",
    &"好吃",
    &"礼貌",
    &"最近",
    &"可以",
    &"失望",
    &"估计",
    &"著名",
    &"朋友",
    &"在	再",
    &"外",
    &"女孩",
    &"黑",
    &"问题",
    &"判断",
    &"烤鸭",
    &"开",
    &"所有",
    &"冰箱",
    &"呀",
    &"舒服",
    &"姓	行	醒",
    &"任何",
    &"周围",
    &"语法",
    &"对不起",
    &"考试",
    &"弄",
    &"正确",
    &"起床",
    &"顺利",
    &"然而",
    &"开始",
    &"作家",
    &"内容",
    &"咖啡",
    &"羡慕",
    &"辛苦",
    &"条件",
    &"工作",
    &"简单",
    &"电影",
    &"招聘",
    &"怀疑",
    &"大概",
    &"关系",
    &"朋",
    &"发生",
    &"好	号",
    &"害怕",
    &"顺便",
    &"餐厅",
    &"现金",
    &"肚子",
    &"公园",
    &"吃惊",
    &"聚会",
    &"抱歉",
    &"看见",
    &"谈",
    &"春节",
    &"季节",
    &"火车站",
    &"复杂",
    &"方便",
    &"社会",
    &"参加",
    &"认识",
    &"勺子",
    &"外面",
    &"附近",
    &"放弃",
    &"学校",
    &"容易",
    &"几	极	寄	即",
    &"父亲",
    &"儿子",
    &"打算",
    &"书	树	输	数",
    &"打招呼",
    &"尽管",
    &"去年",
    &"代表",
    &"七	骑",
    &"字",
    &"住	祝",
    &"明白",
    &"整理",
    &"麻烦",
    &"次",
    &"发",
    &"别人",
    &"医院",
    &"入口",
    &"发现",
    &"激动",
    &"感动",
    &"以后",
    &"右边",
    &"词典",
    &"学	雪",
    &"哪儿	那儿",
    &"上班",
    &"交流",
    &"个子",
    &"站",
    &"商量",
    &"提前",
    &"失败",
    &"岁",
    &"绿",
    &"按",
    &"寒假",
    &"总是",
    &"最后",
    &"上午",
    &"成为",
    &"理想",
    &"证明",
    &"鸡蛋",
    &"气温",
    &"苹果",
    &"门",
    &"后面",
    &"五	无",
    &"大学",
    &"平时",
    &"因为",
    &"身边",
    &"刷牙",
    &"马克",
    &"爱情",
    &"表示",
    &"司机",
    &"既然",
    &"皮肤",
    &"脾气",
    &"极了",
    &"故事",
    &"关注",
    &"因此",
    &"无法",
    &"儿童",
    &"乒乓球",
    &"客厅",
    &"降低",
    &"信封",
    &"约会",
    &"郊区",
    &"认真",
    &"增长",
    &"城市	诚实",
    &"歌舞",
    &"收拾",
    &"网球",
    &"秘书",
    &"礼拜天",
    &"浪费",
    &"暖和",
    &"友谊",
    &"丢",
    &"这儿",
    &"相同",
    &"没关系",
    &"手表",
    &"担心",
    &"压力",
    &"检查",
    &"环保",
    &"十分",
    &"孙子",
    &"班	搬	半",
    &"号码",
    &"管理",
    &"当然",
    &"周",
    &"随便",
    &"阅读",
    &"以为",
    &"解决",
    &"例子",
    &"年级",
    &"美好",
    &"希望",
    &"学期",
    &"印象",
    &"先生",
    &"富",
    &"表扬",
    &"答案",
    &"宾馆",
    &"由于",
    &"推迟",
    &"羽毛球",
    &"今年",
    &"裤子",
    &"发展",
    &"游戏",
    &"任务",
    &"干杯",
    &"禁止",
    &"长	尝	场",
    &"洗澡",
    &"起飞",
    &"经验",
    &"实际	世纪",
    &"一会儿",
    &"俩",
    &"马上",
    &"的	得	地",
    &"跟",
    &"本来",
    &"说话",
    &"上",
    &"帽子",
    &"鸟",
    &"块	快",
    &"原来",
    &"有点	优点",
    &"虽然",
    &"要求",
    &"出院",
    &"回来",
    &"是否",
    &"除了",
    &"我们",
    &"特别",
    &"弹钢琴",
    &"名字",
    &"法律",
    &"本	笨",
    &"了解",
    &"你",
    &"占线",
    &"另外",
    &"星星",
    &"一边",
    &"早",
    &"允许",
    &"博士",
    &"草",
    &"护士",
    &"流行",
    &"怎么办",
    &"篇	骗",
    &"多么",
    &"种	重",
    &"快乐",
    &"道歉",
    &"方式",
    &"两	辆	亮",
    &"幽默",
    &"您",
    &"低	底",
    &"说",
    &"确实",
    &"适应",
    &"特点",
    &"一直",
    &"抽烟",
    &"为什么",
    &"普遍",
    &"听	挺	停",
    &"完全",
    &"游泳",
    &"通知",
    &"短信",
    &"句子",
    &"优秀",
    &"自行车",
    &"理发店",
    &"自己",
    &"打扫",
    &"到处",
    &"奇特",
    &"国际	国籍",
    &"四	死",
    &"参观",
    &"黄河",
    &"小吃",
    &"衣服",
    &"下	夏",
    &"爱迪生",
    &"付款",
    &"相反",
    &"后悔",
    &"理发",
    &"说明",
    &"正常",
    &"包	饱	抱	保",
    &"祝贺",
    &"洗	西",
];

// The longest phrase in the list below has PINYIN_SIZE_MAX characters.
// No need to consider longer slices when checking for match.
// Note: UTF-8 means both (chars == bytes) or (chars != bytes) possible.
pub const PINYIN_SIZE_MAX: usize = 16;

// u32 constants are murmur3 hash of pinyin search keys
pub const MURMUR3_SEED: u32 = 0;
pub static PINYIN: &[u32] = &[
    0x0064c402, // riji
    0x0066ab0e, // xiangjiao
    0x00a9621b, // zhijie
    0x00cd84aa, // xingqu
    0x012707d9, // cai
    0x0224acb9, // dui
    0x025b4a74, // xingbie
    0x028c89c3, // qian
    0x02a44c92, // shuzi
    0x02aaf006, // tang
    0x02c07940, // fenzhong
    0x02e1b450, // juban
    0x0309744f, // haochu
    0x03a09e17, // jiezhe
    0x03a844f5, // chengzuo
    0x04053f6c, // fangxin
    0x04742710, // banshi
    0x04a2598f, // diqiu
    0x04bacedf, // huai
    0x051bfb53, // bian
    0x0522ff8e, // nian
    0x0579cbb1, // juli
    0x05cb4683, // lihai
    0x060e5387, // gonggongqiche
    0x061bd6a6, // jujue
    0x066e8cd4, // chufang
    0x06783105, // shenti
    0x06f93972, // chaoshi
    0x073273ae, // chuxian
    0x074eb454, // zui
    0x0773ada8, // zhuanmen
    0x07a09663, // chunyou
    0x07b145a5, // fannao
    0x07d3e9e6, // kexue
    0x0839255e, // cha
    0x08802645, // shaowei
    0x08bfb9d3, // meili
    0x08c074ea, // liqi
    0x092bfdde, // jihu
    0x09728f95, // fengfu
    0x09c997a0, // wancheng
    0x0a4dbe5c, // bukeqi
    0x0a7ee1e2, // jieshu
    0x0b10072e, // mei
    0x0b2d1aa2, // cuxin
    0x0b5a5eaf, // jiayouzhan
    0x0b712f1a, // lishi
    0x0ba14561, // qiguai
    0x0bcd1c14, // gandao
    0x0c41d2ad, // keji
    0x0c870953, // shenzhi
    0x0c9ce39d, // panzi
    0x0cb3daf4, // zhongwu
    0x0cdf42fc, // aihao
    0x0cf28653, // kaiwanxiao
    0x0db04be3, // laizi
    0x0e41a62d, // wudao
    0x0ea0f6f4, // didian
    0x0eb37000, // nanshou
    0x0ed4eb19, // yinqi
    0x0f1b04e5, // ceng
    0x0f4ec3d1, // jiaozi
    0x0fcaf412, // zhongshi
    0x0fd58239, // cuo
    0x1016fa10, // jilei
    0x10174403, // yanjiu
    0x109913b0, // huanying
    0x10ab5f3d, // pangbian
    0x10d241f9, // haiyang
    0x10de96c5, // wuliao
    0x10f96b81, // tuo
    0x110d2925, // ta
    0x111846f1, // anpai
    0x112c7ac4, // hanyu
    0x114f1b0d, // xiaoyu
    0x117a0fd9, // youqu
    0x11eccee8, // wei
    0x12268b11, // zenme
    0x1226922f, // zunzhong
    0x12303385, // didi
    0x1237f9b2, // zhongjian
    0x126c172f, // chi
    0x129c533c, // kongtiao
    0x129f53dd, // ai
    0x12fba789, // quedian
    0x131dec83, // yagao
    0x134df849, // zhongwen
    0x139ede6a, // youxian
    0x13b014e7, // gaosu
    0x13dd754c, // laohu
    0x1466e660, // darao
    0x14675df4, // xuyao
    0x147cf13e, // zhiyao
    0x14a2319e, // qianbao
    0x14d92534, // youdianr
    0x153bd679, // zhexie
    0x154a4838, // nanguo
    0x15575a99, // jingzheng
    0x15ca03a8, // shuai
    0x15e763b0, // fashao
    0x15ebdc5f, // laji
    0x1652ffd3, // mahu
    0x16819bdf, // shangdian
    0x16a3f922, // shao
    0x16e78217, // heshi
    0x1709131d, // baoming
    0x1752c980, // daoyou
    0x17582235, // ganjue
    0x175fcf67, // liaotianr
    0x17cdd84f, // qiong
    0x17d616ef, // biaozhun
    0x181cff59, // tian
    0x1884693e, // zongjie
    0x188662ea, // zhuyao
    0x189210cd, // zhiliang
    0x18b0f9e8, // zhaoxiangji
    0x18c43239, // yixia
    0x190ac39f, // xiangpi
    0x192fc038, // yihuir
    0x1943c14d, // san
    0x19787c91, // laoshi
    0x1997d8de, // ganjing
    0x1a11bb8b, // huang
    0x1a51791f, // zhuyi
    0x1ac331b5, // shenghuo
    0x1b5754de, // nvhair
    0x1b6436ae, // chenshan
    0x1b7f32f0, // jingju
    0x1b9beb26, // zuoye
    0x1bdf71d5, // yi
    0x1bfaee64, // maojin
    0x1c1baf7d, // liuli
    0x1c45ce9e, // qunzi
    0x1ccc0ccb, // ma
    0x1d10148b, // leng
    0x1d967401, // daodi
    0x1dae932e, // xiangshan
    0x1db16adb, // yaoshi
    0x1dc58a0e, // kou
    0x1df272d0, // la
    0x1e1e0d19, // tizuqiu
    0x1e97b218, // dai
    0x1eb4813c, // nimen
    0x1eb8df51, // yuyan
    0x1ed18529, // lou
    0x1f15329b, // deyi
    0x1f24175c, // jixu
    0x1f7e6bd1, // renming
    0x1fd17ae3, // shushu
    0x20c60fd8, // ranhou
    0x20fbf8a4, // yuanyin
    0x2131fe1b, // han
    0x214bddd2, // mianshi
    0x219d2e9f, // nengli
    0x21ad3abc, // keneng
    0x21c04be2, // xin
    0x220cc0f9, // jiujing
    0x222d0a8c, // zhihao
    0x223b026a, // xiangxin
    0x2271e4aa, // hou
    0x2297f0e8, // beizi
    0x22afc846, // lvshi
    0x22de09b7, // xiuxi
    0x23082a40, // jiji
    0x2389db75, // jiayou
    0x238b1c79, // langman
    0x23bab692, // renwei
    0x23eb2fec, // jinzhang
    0x24416c95, // zhuozi
    0x246675db, // qingkuang
    0x24f7c245, // beijing
    0x25042309, // lvxing
    0x254f6997, // shihe
    0x259327b8, // fanyi
    0x25965895, // zhangfu
    0x25f2705d, // taolun
    0x2622862f, // dashiguan
    0x26f20d98, // fense
    0x26f4dd77, // lu
    0x2788bb71, // bizi
    0x27e38a91, // nianling
    0x27eba344, // wuran
    0x28ba020d, // he
    0x28c3270e, // youyisi
    0x29c40065, // wangji
    0x29c64f88, // jingcha
    0x2a192fe8, // xinglixiang
    0x2a6757ee, // yue
    0x2a7a3c16, // haizi
    0x2ab626b7, // daifu
    0x2ae97113, // jianqing
    0x2b038801, // a
    0x2b1ca8fb, // zhao
    0x2b53f723, // meimei
    0x2b8c40aa, // budebu
    0x2bc93f00, // jieshao
    0x2bdeba4a, // nv
    0x2bf6a428, // geng
    0x2c1a14a9, // youqi
    0x2c79f9c7, // weixian
    0x2c9b752b, // jizhe
    0x2caf8201, // jihua
    0x2cbeea3b, // miao
    0x2cc63e0d, // shuang
    0x2cdb24c7, // yisi
    0x2ce0a73b, // gege
    0x2cf16df9, // gongli
    0x2d143d20, // bingqie
    0x2da03ddc, // suoyi
    0x2dbe86a3, // jianshao
    0x2df4751f, // kanfa
    0x2df8ca17, // zhongyao
    0x2e7fc924, // anzhao
    0x2f2cc657, // shengbing
    0x2f4bf29c, // yezi
    0x2f58a6ef, // baba
    0x2f896fa8, // qishi
    0x2fb1da28, // yangguang
    0x2fcf7ad7, // kuangquanshui
    0x2fdfc442, // xinxian
    0x3013ac33, // xishoujian
    0x307329ec, // xiamian
    0x3074029a, // diao
    0x3112abbb, // jian
    0x3127fbb0, // yisheng
    0x31321647, // shengming
    0x31379d58, // xiaoshi
    0x315a9372, // guke
    0x31b2d1e8, // shuiping
    0x32378950, // biaoyan
    0x325bd011, // kuaizi
    0x32ccd10f, // zhiye
    0x32e7501c, // guanxin
    0x32f18ca5, // xingfu
    0x32f603d3, // bijiben
    0x33029bb2, // shangwang
    0x335efa35, // bucuo
    0x336eb256, // xiexie
    0x337a6ddc, // xinxin
    0x3387e972, // yiyang
    0x338d840b, // kong
    0x34017b0d, // ganqing
    0x341cf66c, // jiaotong
    0x342e35e7, // nan
    0x343026e6, // suan
    0x34855b85, // piaoliang
    0x3486c18e, // xinxi
    0x34dac768, // heiban
    0x34f97a15, // qianbi
    0x34ff48c4, // hege
    0x350285e5, // mifan
    0x3513b272, // shafa
    0x3520b8db, // tui
    0x35574bdc, // tiao
    0x355b2cd8, // nali
    0x35b11ea8, // guanyu
    0x35b84211, // xinnian
    0x35d72b2e, // xuanze
    0x3630e479, // yu
    0x3653935e, // fangfa
    0x36a8b5c0, // guoqu
    0x370e27c8, // dadao
    0x3772a371, // jidao
    0x377422f2, // tingshuo
    0x37a76a6f, // shengyin
    0x37d75ffa, // yazhou
    0x38dd51ec, // kelian
    0x38e42cc1, // shen
    0x38e6cca1, // deng
    0x39473889, // xiaoyuan
    0x3954f551, // cun
    0x3998c7bf, // jingguo
    0x399e4b2d, // yiding
    0x39e77e63, // yeye
    0x3a1be3f6, // meiyou
    0x3a211011, // genju
    0x3a86a04b, // gan
    0x3acad72a, // yun
    0x3b668005, // shengyi
    0x3b9ad4ac, // yange
    0x3bb76bba, // qing
    0x3bbda547, // quanbu
    0x3bcb505e, // shei
    0x3c258eb1, // baohu
    0x3c7beae3, // zhishi
    0x3d54c1eb, // paidui
    0x3dd06b04, // guli
    0x3dfaad2a, // du
    0x3e1b056e, // teng
    0x3e27a350, // jieguo
    0x3e2f25f5, // yaoqing
    0x3e8160c4, // ku
    0x3ea0533c, // da
    0x3ecd8f70, // bei
    0x3efd3d07, // jinxing
    0x3f0010b7, // zaijian
    0x3f44f44f, // lijie
    0x3fa3f5f0, // zenmeyang
    0x3ffcb9de, // chun
    0x401d5c86, // kan
    0x40407dd1, // chuzuche
    0x404e8c07, // yashua
    0x40758501, // biye
    0x40a715a3, // dazhen
    0x40c18c23, // qilai
    0x40cdb646, // can
    0x41239d1f, // zhengzai
    0x41982ff6, // gei
    0x41a7eb65, // qiu
    0x422f78c1, // dedao
    0x423f8b81, // pang
    0x424934f2, // qubie
    0x4267dbd0, // xiayu
    0x428ecfbc, // liuyiertongjie
    0x42925447, // putong
    0x42a78f37, // milu
    0x42de69fc, // xiguan
    0x433b044f, // shuliang
    0x436332e3, // gongtong
    0x4364c18f, // fangjian
    0x4383a6cd, // yuan
    0x4422a8d7, // xinqing
    0x446ad11e, // yingpin
    0x4489afdc, // nandao
    0x44d6183f, // ye
    0x44f9bd32, // fengjing
    0x45735c0a, // qizhong
    0x457a7cb1, // jingshen
    0x457cdc66, // jianglai
    0x459bd1a2, // xuexi
    0x45ad4586, // gouwu
    0x45cb4a97, // juede
    0x45e0a7fb, // mama
    0x45fb32d9, // jingran
    0x46254d78, // kongr
    0x4648d963, // zuowei
    0x4680771d, // feiji
    0x46828705, // beifang
    0x46b85ca4, // quan
    0x46c58c7c, // baozhi
    0x46f91ddc, // changqi
    0x4736ac0c, // ciyu
    0x47baba69, // qiaokeli
    0x47c9f3a0, // mingtian
    0x47e7e652, // che
    0x4802f27f, // ri
    0x48b2f867, // xingge
    0x48df8c54, // xiaopengyou
    0x48e8768e, // cesuo
    0x4911ec49, // naozhong
    0x493bfe19, // nainai
    0x495e2f55, // sanbu
    0x4986e51d, // niunai
    0x498befc1, // bisai
    0x498ccedf, // keren
    0x4992173e, // mima
    0x49a77388, // putao
    0x49d42ae9, // xihongshi
    0x4a36e35a, // yanjing
    0x4a4d0545, // huida
    0x4a4ec1cd, // miantiao
    0x4a583d3b, // jingji
    0x4b2eef21, // bujin
    0x4b4bdfc4, // zuoke
    0x4b52ab6f, // dang
    0x4b646cf1, // hen
    0x4b9d7f61, // chaoguo
    0x4bc7e70d, // shoudujichang
    0x4bdb20e5, // caidan
    0x4c870bfd, // ti
    0x4cd86be1, // jiaoshi
    0x4d132bff, // yanse
    0x4d403eca, // huiyi
    0x4d8b28e0, // weidao
    0x4d8ce0a2, // gaibian
    0x4dba017f, // zhen
    0x4ea7f874, // tushuguan
    0x4eabed83, // xuesheng
    0x4ebe4829, // xianggua
    0x4ebfe8f7, // mi
    0x4ee55a27, // er
    0x4f0472a1, // fangmian
    0x4f11ea91, // yushi
    0x4f253418, // chifan
    0x4f730389, // shoubuliao
    0x4f9b7078, // shenme
    0x4fc3f6d6, // xiongmao
    0x503331da, // jingzi
    0x50603d0b, // cong
    0x5083f59b, // xiawu
    0x50bfb398, // huahua
    0x50dd5424, // xiaoxin
    0x511a0060, // zhidao
    0x5166139a, // gaoxing
    0x517cf932, // qingchu
    0x51e75c37, // ge
    0x51e7b249, // fangshujia
    0x520a3fb4, // nvxing
    0x527b4d3d, // fen
    0x52c4b867, // fuhe
    0x52cbec2b, // gebo
    0x52ed9733, // shuijiao
    0x52ef53ff, // haishi
    0x52f6b88d, // goumai
    0x530f241b, // gangcai
    0x5342e129, // laideji
    0x537e5991, // zhunshi
    0x53b0d6ce, // zhaogu
    0x53bbcee2, // zhidai
    0x53dc824d, // wenhua
    0x53f3356b, // youhao
    0x5463d9b6, // hulianwang
    0x5473b4ac, // shiqing
    0x54984eb3, // duimian
    0x54da69f0, // jiao
    0x550c465d, // shuxi
    0x55583905, // xingqi
    0x5570e771, // ju
    0x55e29439, // zeren
    0x55fea07a, // jiankang
    0x564b45a9, // dengjipai
    0x565a2f07, // jishu
    0x566af38a, // shouru
    0x56851684, // difang
    0x56cd7969, // gai
    0x573f589d, // ke
    0x577e194e, // jingse
    0x57885cab, // shengqi
    0x57980e5e, // weile
    0x579bbd6f, // jichu
    0x57b5e5ac, // anquan
    0x57eab98a, // keshi
    0x580463b4, // lajitong
    0x5807fd44, // shuizhao
    0x58784d5d, // meirenyu
    0x58c3dc4b, // daban
    0x59290d00, // jieyue
    0x59345b2a, // zeng
    0x5975bdcc, // li
    0x599424f0, // chufa
    0x5a32ea82, // qiao
    0x5a7c6a5c, // chuang
    0x5abdff6a, // youming
    0x5b080384, // tongguo
    0x5b11b835, // na
    0x5b1f4f22, // taoyan
    0x5b21d9cd, // ming
    0x5b223166, // bixu
    0x5b8b7e6a, // liangcha
    0x5b8c7393, // piping
    0x5bc5023b, // chidao
    0x5c16af7d, // shangchang
    0x5c26e17a, // kongqi
    0x5c36dc00, // xinwen
    0x5c4820f6, // gongjin
    0x5c732326, // shui
    0x5c989bec, // liuxue
    0x5d238ea5, // muqin
    0x5d364508, // biaoge
    0x5d40765e, // changjiang
    0x5d5b7bdb, // mianbao
    0x5da2611a, // tongyi
    0x5db7d36f, // yijing
    0x5db8ddde, // zhongqiujie
    0x5ddd9eed, // kongpa
    0x5dfa15f6, // dou
    0x5e977bb1, // zixi
    0x5ece1f41, // liu
    0x5ed6dc1c, // jichang
    0x5f3eeb44, // guafeng
    0x5f4ee28b, // yijian
    0x5fd4237b, // nei
    0x5ff89d5e, // yanchu
    0x605c343c, // wanr
    0x605f6511, // zhuanye
    0x606e4950, // guozhi
    0x6070885a, // xiao
    0x60761940, // guocheng
    0x60dcf8fb, // manyi
    0x60f63615, // zuotian
    0x60f66228, // jiang
    0x611bf763, // jiangluo
    0x61bedf2e, // wulun
    0x61d8d67e, // lai
    0x61fcae95, // pianyi
    0x624e9084, // xiaohuozi
    0x62c02f39, // fuxi
    0x62e8f20a, // laibuji
    0x636f6f38, // hezi
    0x63722fd9, // ditie
    0x642c100c, // jingcai
    0x643a0de5, // biru
    0x6545b0df, // zuozhe
    0x65580ab2, // duo
    0x655f8310, // banfa
    0x65a1becd, // shihou
    0x65b6597b, // ganxingqu
    0x65cc3c60, // qu
    0x65f1061b, // dazhe
    0x6662cfc6, // yangzi
    0x6666c7e6, // senlin
    0x66866568, // tongyang
    0x66903d6b, // gua
    0x66a0c4fa, // youju
    0x66a70ed7, // qingsong
    0x66a9f259, // dianziyoujian
    0x66aaf7ba, // yongyuan
    0x66efe745, // yigong
    0x672163ce, // bijiao
    0x6754d280, // xian
    0x67a25ec2, // mang
    0x67bad25b, // xiaoqu
    0x68411b22, // youguan
    0x685b42c0, // yuanyi
    0x68940d2f, // qinqi
    0x68a34725, // liangkuai
    0x68b73f5b, // feichang
    0x692fecca, // tigao
    0x69353e72, // xingfen
    0x695bf5b7, // bai
    0x6963f13b, // chuchai
    0x69837086, // keai
    0x69d00d8c, // yinyue
    0x69ebf985, // zang
    0x6a4884bf, // wazi
    0x6acf341e, // yuxi
    0x6b0548dd, // ba
    0x6b230d9c, // hai
    0x6ba31e94, // ren
    0x6bb47f59, // zhuan
    0x6bd50d6e, // tiyuguan
    0x6bed8fdb, // binggan
    0x6c09bd83, // baozheng
    0x6c11a78e, // huiyuanka
    0x6c54b99a, // hong
    0x6c5cde4c, // fangxiang
    0x6c78827a, // yuanliang
    0x6c7a8607, // nuli
    0x6cdd5fa2, // bianhua
    0x6ce60fc1, // kaolv
    0x6d15fe50, // chengji
    0x6d87d5b9, // liaotian
    0x6db0456b, // yiqian
    0x6de82b21, // zhongguo
    0x6e6fe2a0, // gaosugonglu
    0x6f09ac76, // yiqie
    0x6f243409, // qizi
    0x6f2cf67e, // juxing
    0x6f458eed, // zanmen
    0x6fc44ca2, // hongse
    0x700167e7, // xhileng
    0x7016c87d, // cheng
    0x7020bfaf, // paobu
    0x7052d470, // mao
    0x70793127, // xiaoguo
    0x70dda04c, // zhongdian
    0x7178cdb9, // zhenghao
    0x71aeb78b, // ruguo
    0x71cb0967, // reqing
    0x71e69095, // zhi
    0x7210a02f, // zhiwu
    0x721c1950, // ayi
    0x72257568, // zhengshi
    0x7225d325, // erqie
    0x72bb4254, // likai
    0x72bd7076, // qianmian
    0x72cc6f1f, // neng
    0x72e24c00, // fandui
    0x7314ceff, // shenqing
    0x73353ca8, // ca
    0x7366e9e3, // gongzi
    0x73c793e0, // yizi
    0x73f4be6d, // xiaoshuo
    0x745f8573, // chao
    0x747f191f, // bangzhu
    0x748b6e2f, // bufen
    0x74ad811f, // zhishao
    0x74cbf133, // anshi
    0x74e40413, // yan
    0x75041f3b, // shi
    0x75344d45, // qita
    0x757ffc05, // xie
    0x758fa66b, // jintian
    0x75e81e7b, // qingjia
    0x762078ea, // shouhuoyuan
    0x7654ada5, // diaocha
    0x7694398a, // ziran
    0x76959834, // rang
    0x76d92d04, // liuxie
    0x76f44787, // shizai
    0x76fb9d72, // song
    0x770c64ef, // kending
    0x77b5d6d8, // suliaodai
    0x77c80353, // anna
    0x77d084dc, // yinggai
    0x780f45eb, // danshi
    0x7833c2b3, // cailiao
    0x78b05f75, // zhe
    0x78c9613b, // yiqi
    0x78f21b81, // yukuai
    0x7963af41, // lengjing
    0x799be6fb, // zhaopian
    0x79a72591, // lvyou
    0x79befddb, // huxiang
    0x79e58a42, // zazhi
    0x79f8600a, // gongsi
    0x7a1f4161, // yanyuan
    0x7a206d78, // mianfei
    0x7a20f5c3, // butong
    0x7a681a2a, // jiejie
    0x7aa343a4, // huodong
    0x7abf9117, // pei
    0x7adbd611, // lianxi
    0x7ae05d22, // zhua
    0x7ae9cb6c, // xiang
    0x7b0f0d0d, // rengran
    0x7b50924f, // zanshi
    0x7b6a60fc, // gao
    0x7b777e53, // huode
    0x7b7a7f2b, // kexi
    0x7b913ade, // qihou
    0x7b9599ba, // zuo
    0x7bbbd15c, // yudao
    0x7bd18374, // jiehun
    0x7be82dd9, // guangbo
    0x7c0b3dd5, // shijie
    0x7cc8ea46, // jueding
    0x7cd44817, // zou
    0x7d093749, // hangban
    0x7dd2b783, // jihui
    0x7e8248d8, // chabuduo
    0x7e96d28d, // guanggao
    0x7ea2cc90, // shijian
    0x7f133fdf, // jiaju
    0x7f892426, // bi
    0x7faca4fb, // meitian
    0x802bbf49, // hongjiu
    0x80354a78, // bie
    0x80405073, // hua
    0x804744c4, // e
    0x80a2d70f, // tiankong
    0x8117b45d, // dayue
    0x814c32de, // yinliao
    0x81705da0, // jie
    0x8256cadb, // yong
    0x82c1940a, // tongqing
    0x835174e5, // xiyin
    0x8392eff8, // taidu
    0x83aadb62, // yang
    0x845079e8, // dajia
    0x84539fcc, // haoxiang
    0x8477cf48, // dong
    0x8483fd69, // guo
    0x84cd426d, // xiaoxi
    0x84e58f29, // ditu
    0x84f0ab9a, // que
    0x84fe8bc5, // guan
    0x851bd243, // bing
    0x854913fb, // baifenzhi
    0x85ef6284, // yanzhong
    0x8607a96a, // shifu
    0x8629b4dd, // meng
    0x86a4b392, // yingxiang
    0x86b63cc6, // duche
    0x86e73439, // chuanzhen
    0x86f8ea22, // duan
    0x87014331, // huozhe
    0x87123599, // kaixin
    0x87b53c9f, // jianmian
    0x87cab238, // pijiu
    0x8897c6ca, // yundong
    0x88d2865d, // naixin
    0x8907650d, // yangcheng
    0x89091e46, // fumu
    0x8928ad18, // qici
    0x8aa7dad3, // kunnan
    0x8aad5ac7, // haixiu
    0x8ac05f7a, // dayin
    0x8bb8da89, // jianfei
    0x8bd50111, // huo
    0x8bebc618, // re
    0x8bf2dc4d, // sheng
    0x8bf41cd9, // suizhe
    0x8c24074b, // gang
    0x8cac02bf, // xigua
    0x8ccb1eaf, // queshao
    0x8d1567d6, // daizi
    0x8d444b30, // chenggong
    0x8d55c4f3, // yangrou
    0x8e85d189, // linju
    0x8eb616fd, // shoudao
    0x8ef6f951, // yin
    0x8f716e0f, // zhongyu
    0x8f853336, // kesou
    0x8fad9710, // bishi
    0x8fdfbfa1, // jiaoyu
    0x8ff7f7ec, // shan
    0x90017f36, // toufa
    0x9014d5a5, // yiban
    0x9039e2ce, // chusheng
    0x9074d186, // shouxian
    0x9087d380, // duanlian
    0x90a712ae, // ganmao
    0x914f4586, // zuobian
    0x916e8f20, // bangmang
    0x91703613, // hanzi
    0x9188c552, // meiguo
    0x9206c60c, // qianwan
    0x92373b19, // lingqian
    0x926369c2, // youxiao
    0x927a267a, // qianzheng
    0x92a6e898, // shuoshi
    0x92e26e59, // chongxin
    0x92ed3254, // shuxue
    0x931ca258, // daoshihou
    0x93299194, // xuduo
    0x9369aec6, // zixin
    0x9370ab8b, // dianshi
    0x938292e6, // huopo
    0x941009e2, // jide
    0x9482e250, // lei
    0x94969f2f, // po
    0x94be0858, // reng
    0x9527b913, // yishu
    0x95ce8623, // biao
    0x95e0d221, // yidianr
    0x968c10fc, // tongxue
    0x96a40bd5, // wen
    0x96b25b3c, // dongxi
    0x96d4b796, // fuwuyuan
    0x96da5ff3, // lian
    0x972b02f1, // bang
    0x975f0121, // baozi
    0x978f4c48, // zhang
    0x979a96ad, // ling
    0x97c3d221, // tai
    0x9816d70e, // piao
    0x9863d07e, // shengri
    0x98aa2ab1, // wangwang
    0x9935279e, // lan
    0x994975ad, // man
    0x999515ef, // conglai
    0x9a44ad3f, // zaoshang
    0x9a73395f, // dangao
    0x9a7a8ce0, // ne
    0x9a813b22, // dangshi
    0x9ab196f7, // miandui
    0x9ab31b6e, // bangongshi
    0x9ab6563d, // dongzuo
    0x9ad5a475, // xinxiangan
    0x9aea3ee0, // shuiguo
    0x9b41271e, // jin
    0x9b5613f0, // zhunbei
    0x9b6b1e59, // zengjia
    0x9b9741e3, // xiaohua
    0x9badda8e, // zhichi
    0x9be5e847, // xiaojie
    0x9c211f6f, // chu
    0x9c73f803, // wuhui
    0x9c793211, // shiyong
    0x9ca8655e, // jiage
    0x9cec3981, // houlai
    0x9d135428, // zhide
    0x9d9db27a, // shibangongbei
    0x9db153c2, // chuan
    0x9dd21b18, // dalanqiu
    0x9ded99fd, // guiding
    0x9e4c30e0, // biji
    0x9e54efec, // yinyuehui
    0x9eb469c4, // hui
    0x9fd2e93b, // mudi
    0x9fd9a2c3, // erduo
    0xa002a756, // changge
    0xa03812ca, // ying
    0xa03af657, // guanzhong
    0xa047d6f5, // putonghua
    0xa05c2ac5, // yueliang
    0xa08930f5, // gongfu
    0xa0a9dba6, // nianqing
    0xa0e9e85b, // guangdongsheng
    0xa0fabb7d, // sudu
    0xa108bd2d, // fang
    0xa10cceb0, // buguo
    0xa1deb863, // fuyin
    0xa1ef34e1, // gui
    0xa1f15f54, // yexu
    0xa20b18e7, // taiyang
    0xa275d2c7, // jia
    0xa27e9174, // yibanlaishuo
    0xa2c47207, // pashan
    0xa3b76c06, // jiaoao
    0xa403b18c, // liwu
    0xa4748bb7, // tigong
    0xa47ca216, // nuan
    0xa4bbc227, // jianyi
    0xa4d2880b, // jingchang
    0xa4d69b54, // pailie
    0xa4e62c5b, // congming
    0xa5b5b625, // shanghai
    0xa5c48454, // shunxu
    0xa5f8f54a, // pingzi
    0xa64c34e0, // guang
    0xa65a5200, // wang
    0xa6d467bc, // lukou
    0xa6e16dd1, // dizhi
    0xa70eea9d, // jiaban
    0xa7925668, // budan
    0xa809ac3b, // xiuli
    0xa860d93c, // jiaoshou
    0xa8e4485f, // tianqi
    0xa8fe8794, // fangsong
    0xa967d647, // zhiyou
    0xa9a157bd, // dadianhua
    0xa9af5df2, // guyi
    0xa9bd9061, // duihua
    0xa9f269d4, // tongshi
    0xa9fdebc9, // ouer
    0xaa2ca6f1, // guanjian
    0xaa369db7, // minzu
    0xaa54d8a2, // fouze
    0xaab64a11, // weishengjian
    0xab485a9d, // dei
    0xab9ead85, // guai
    0xabd9b778, // pixie
    0xabdff14c, // wo
    0xac0a2f3f, // yao
    0xac38acaa, // huzhao
    0xac58c0dd, // jiaqian
    0xac90ab3d, // dawei
    0xacbdb110, // guojia
    0xad02ce27, // fangzi
    0xad083e96, // jieri
    0xad0ae689, // jieshou
    0xad50bf49, // dianti
    0xad7663de, // changcheng
    0xad8b03fc, // diyi
    0xadc64d42, // xiaoxiao
    0xade575df, // cuowu
    0xae0283fa, // xianzai
    0xae33ea32, // wangzhan
    0xae4013dd, // jing
    0xae58d824, // xinyongka
    0xae5c11e3, // xiangxi
    0xae707a35, // shou
    0xae7d8902, // luan
    0xaf3b6010, // duiyu
    0xaf94f6b0, // zan
    0xafbb6cca, // wenzhang
    0xafbd5923, // anjing
    0xb0290937, // zu
    0xb0a3433b, // xiaozhang
    0xb10b3adf, // yonggan
    0xb1293058, // tiyu
    0xb1989693, // jianchi
    0xb1a3e2ce, // zhaoji
    0xb1d453ef, // zuoyong
    0xb2e49787, // wanshang
    0xb2fa8b7f, // dao
    0xb32ab687, // dian
    0xb34e22e8, // mai
    0xb3a027cc, // sunyue
    0xb3aa2f17, // diannao
    0xb3b96c38, // le
    0xb462a1f6, // jiu
    0xb4890163, // shouji
    0xb491b801, // zhenzheng
    0xb5b634b7, // zhunque
    0xb5cf27a5, // wan
    0xb606543d, // zuoyou
    0xb606a933, // duoshao
    0xb620d462, // waidi
    0xb63e9487, // jieshi
    0xb674e084, // tixing
    0xb682d0b4, // gou
    0xb6bbc43a, // renao
    0xb6c23fc0, // xihuan
    0xb728f4be, // turan
    0xb7468d14, // nver
    0xb7586e58, // wendu
    0xb7a42296, // shoudu
    0xb7b8687a, // huan
    0xb7ca20b8, // fuze
    0xb7e0cb12, // changjiangdaqiao
    0xb7fa807b, // you
    0xb8f0c61d, // jishi
    0xb9032e73, // tiaowu
    0xb921d0aa, // huanjing
    0xb921f54b, // dongwu
    0xb9e20d30, // chuanghu
    0xb9f6b320, // xianhua
    0xba14ea01, // bu
    0xba48dc97, // yinhang
    0xbae0bb57, // fandian
    0xbae17435, // kun
    0xbb98cd6d, // zhoumo
    0xbbaf703c, // zuihao
    0xbc4b39bf, // lin
    0xbc860009, // kele
    0xbca44288, // buguan
    0xbcb0f2db, // lao
    0xbce6edcf, // jiangjin
    0xbd0c7bca, // jingli
    0xbd25ac90, // liru
    0xbd81810e, // jiemu
    0xbd845e8c, // ganxie
    0xbd860937, // shangxin
    0xbda12edd, // bushao
    0xbdb54025, // fangdong
    0xbdb5e511, // haochi
    0xbdf5f795, // limao
    0xbe53bf53, // zuijin
    0xbedeecb4, // keyi
    0xbef2af1c, // shiwang
    0xbf1175fa, // guji
    0xbf56008d, // zhuming
    0xbf82340c, // pengyou
    0xbfc246ee, // zai
    0xbfcb1771, // wai
    0xc05ed29e, // nvhai
    0xc0a5b14c, // hei
    0xc0ca457d, // wenti
    0xc116c6da, // panduan
    0xc169c6bd, // kaoya
    0xc17173bf, // kai
    0xc1c09089, // suoyou
    0xc1e3f2b1, // bingxiang
    0xc1fd490d, // ya
    0xc2a17ef4, // shufu
    0xc2dfb63d, // xing
    0xc30cacd4, // renhe
    0xc3292078, // zhouwei
    0xc3379e70, // yufa
    0xc3c5e911, // duibuqi
    0xc3fab99f, // kaoshi
    0xc3fafe97, // nong
    0xc411d849, // zhengque
    0xc44b3041, // qichuang
    0xc48db364, // shunli
    0xc58bc5e9, // raner
    0xc6c173bd, // kaishi
    0xc6eb8d31, // zuojia
    0xc70e1747, // neirong
    0xc753ce29, // kafei
    0xc75a8a5d, // xianmu
    0xc75f7576, // xinku
    0xc76da511, // tiaojian
    0xc787632a, // gongzuo
    0xc83994b1, // jiandan
    0xc850b631, // dianying
    0xc8778213, // zhaopin
    0xc8a12456, // huaiyi
    0xc8a94a3e, // dagai
    0xc91b2d35, // guanxi
    0xc92a3ab2, // peng
    0xc9bc3ba4, // fasheng
    0xca2f57ac, // hao
    0xca92ce33, // haipa
    0xcb2f3e7a, // shunbian
    0xcb4c20be, // canting
    0xcb90a48e, // xianjin
    0xcba88322, // duzi
    0xcbb3b656, // gongyuan
    0xcc07b367, // chijing
    0xcc172003, // juhui
    0xcc315533, // baoqian
    0xcc352efa, // kanjian
    0xcc65a9b7, // tan
    0xcc8e4c2a, // chunjie
    0xccbd7c5e, // jijie
    0xccc34006, // huochezhan
    0xcd217f7e, // fuza
    0xcd69afeb, // fangbian
    0xcdc56e2c, // shehui
    0xcdd3e180, // canjia
    0xce7f3ff6, // renshi
    0xcec55f91, // shaozi
    0xcec71cfe, // waimian
    0xcef4a2c9, // fujin
    0xcf252a59, // fangqi
    0xcf8520e6, // xuexiao
    0xcfbfd7db, // rongyi
    0xd004cd1a, // ji
    0xd05d7fe3, // fuqin
    0xd0643106, // erzi
    0xd0c3681d, // dasuan
    0xd0cb7b07, // shu
    0xd12b2952, // dazhaohu
    0xd159ec94, // jinguan
    0xd1fb4564, // qunian
    0xd22b13ff, // daibiao
    0xd29410ea, // qi
    0xd2e71433, // zi
    0xd33c3f80, // zhu
    0xd3c48b06, // mingbai
    0xd3ce85bb, // zhengli
    0xd4061506, // mafan
    0xd44f3c2f, // ci
    0xd4947e78, // fa
    0xd4c025f3, // bieren
    0xd4daa2b9, // yiyuan
    0xd4fb06b3, // rukou
    0xd5170c42, // faxian
    0xd52384c6, // jidong
    0xd528049c, // gandong
    0xd54d2d1e, // yihou
    0xd59a85f7, // youbian
    0xd5c7dd0f, // cidian
    0xd5fb3b8f, // xue
    0xd67e5c1b, // nar
    0xd699a2e4, // shangban
    0xd6be135a, // jiaoliu
    0xd6c1883c, // gezi
    0xd72a3c76, // zhan
    0xd751a589, // shangliang
    0xd7c4f526, // tiqian
    0xd8e4499b, // shibai
    0xd93ffe6d, // sui
    0xd94b205b, // lv
    0xd964aa5e, // an
    0xd96be96f, // hanjia
    0xd9e8a13f, // zongshi
    0xda0f11ae, // zuihou
    0xda3e1bdd, // shangwu
    0xda843ae8, // chengwei
    0xdaa78ebc, // lixiang
    0xdaad2c9c, // zhengming
    0xdafe3a60, // jidan
    0xdb6fdaea, // qiwen
    0xdb7038c0, // pingguo
    0xdc091cdb, // men
    0xdc218cda, // houmian
    0xdc23a67d, // wu
    0xdc29114e, // daxue
    0xdc717ea1, // pingshi
    0xdc7b1283, // yinwei
    0xdcbc4498, // shenbian
    0xdcbded0b, // shuaya
    0xdcd83672, // make
    0xdcef464c, // aiqing
    0xdcfcd07b, // biaoshi
    0xdd79dcca, // siji
    0xde5ec244, // jiran
    0xdedb69f4, // pifu
    0xdf1538da, // piqi
    0xdf4960a7, // jile
    0xdf8f7cad, // gushi
    0xdfcfd695, // guanzhu
    0xe019261a, // yinci
    0xe0377fb9, // wufa
    0xe03a3110, // ertong
    0xe099ac4c, // pingpangqiu
    0xe0a293e3, // keting
    0xe0d29c56, // jiangdi
    0xe1c82031, // xinfeng
    0xe21127ab, // yuehui
    0xe214b1b1, // jiaoqu
    0xe228abf0, // renzhen
    0xe2545efc, // zengzhang
    0xe2ce6132, // chengshi
    0xe2ced9ed, // gewu
    0xe2d74098, // shoushi
    0xe31102fa, // wangqiu
    0xe320a7ed, // mishu
    0xe323da02, // libaitian
    0xe33601c8, // langfei
    0xe34bf336, // nuanhuo
    0xe3ebee27, // youyi
    0xe3f66bf2, // diu
    0xe4974952, // zher
    0xe4aa50a8, // xiangtong
    0xe4c2ad4c, // meiguanxi
    0xe51d94f6, // shoubiao
    0xe54199ee, // danxin
    0xe5434120, // yali
    0xe55d65aa, // jiancha
    0xe57c2572, // huanbao
    0xe5b4dccf, // shifen
    0xe5d40c64, // sunzi
    0xe60f35ed, // ban
    0xe623d7ff, // haoma
    0xe6c9c065, // guanli
    0xe70b33b7, // dangran
    0xe7202d60, // zhou
    0xe7894f9b, // suibian
    0xe842ed48, // yuedu
    0xe8ba72e8, // yiwei
    0xe8c084f8, // jiejue
    0xe9887bfc, // lizi
    0xe99cf5e9, // nianji
    0xe99e8c8b, // meihao
    0xe9b0f307, // xiwang
    0xe9e04cf8, // xueqi
    0xea3fe0d1, // yinxiang
    0xea7e8225, // xiansheng
    0xea9aba44, // fu
    0xeab0102f, // biaoyang
    0xeac1e8d8, // daan
    0xeaf74612, // binguan
    0xeb4931c3, // youyu
    0xeb5cf2ea, // tuichi
    0xeb90e40b, // yumaoqiu
    0xeb98da8a, // jinnian
    0xeb9ef73d, // kuzi
    0xebe113d9, // fazhan
    0xec10fcc7, // youxi
    0xec4c053f, // renwu
    0xec5b8bd0, // ganbei
    0xec772349, // jinzhi
    0xec90a46b, // chang
    0xeca9ae7a, // xizao
    0xecbeb06b, // qifei
    0xed26713e, // jingyan
    0xed7a4d33, // shiji
    0xedab1aa9, // yihuier
    0xee52907a, // lia
    0xee65070d, // mashang
    0xee85a44e, // de
    0xee92354e, // gen
    0xeea63a7d, // benlai
    0xeeaa9fd4, // shuohua
    0xef157a07, // shang
    0xef193a11, // maozi
    0xef43bc12, // niao
    0xef551fdf, // kuai
    0xef6e69e0, // yuanlai
    0xef76c650, // youdian
    0xefc0c0bf, // suiran
    0xefc50c8f, // yaoqiu
    0xefdd6e33, // chuyuan
    0xf021f93c, // huilai
    0xf02bb7fe, // shifou
    0xf03c8900, // chule
    0xf0744722, // women
    0xf0d4b9ac, // tebie
    0xf0d5582a, // tangangqin
    0xf10693cb, // mingzi
    0xf17cd0ce, // falv
    0xf1f2bfbf, // ben
    0xf2968d64, // liaojie
    0xf296ff37, // ni
    0xf29b70e3, // zhanxian
    0xf2e0ee9d, // lingwai
    0xf33e8264, // xingxing
    0xf34478df, // yibian
    0xf3c94102, // zao
    0xf3d22753, // yunxu
    0xf420e8b8, // boshi
    0xf427743c, // cao
    0xf4542577, // hushi
    0xf457db13, // liuxing
    0xf469ad3a, // zenmeban
    0xf4858adf, // pian
    0xf522fcab, // duome
    0xf5246271, // zhong
    0xf543a10c, // kuaile
    0xf57d52e9, // daoqian
    0xf6015c6f, // fangshi
    0xf60d2fe0, // liang
    0xf63e91b3, // youmo
    0xf6534f28, // nin
    0xf6610b71, // di
    0xf680bf70, // shuo
    0xf685e750, // queshi
    0xf71c7081, // shiying
    0xf72007b1, // tedian
    0xf72f42a7, // yizhi
    0xf781c9b4, // chouyan
    0xf79391a5, // weishenme
    0xf7964436, // pubian
    0xf7e0f597, // ting
    0xf7f614bf, // wanquan
    0xf81eea45, // youyong
    0xf89d661e, // tongzhi
    0xf8db01db, // duanxin
    0xf92ee2ab, // juzi
    0xf9927382, // youxiu
    0xfa24747b, // zixingche
    0xfa3eebe1, // lifadian
    0xfa620cbd, // ziji
    0xfb5257d3, // dasao
    0xfb5f1c35, // daochu
    0xfb753730, // qite
    0xfc02109b, // guoji
    0xfc75a0c0, // si
    0xfc8dd498, // canguan
    0xfdbb23df, // huanghe
    0xfdc5e218, // xiaochi
    0xfdc7db47, // yifu
    0xfe255a33, // xia
    0xfe7e4391, // aidisheng
    0xfed27924, // fukuan
    0xfef35f00, // xiangfan
    0xff138648, // houhui
    0xff21f487, // lifa
    0xff649877, // shuoming
    0xff972de4, // zhengchang
    0xffb809b8, // bao
    0xffbe5bb3, // zhuhe
    0xfffc53b6, // xi
];

// Tuples are (normalized_pinyin, 词语) from early in vocab file code
// generation precompute pipeline. These correspond closely to lines of
// vocab .tsv files prior to any sorting or merging of duplicates.
#[cfg(test)]
pub static PINYIN_CIYU_TEST_DATA: &[(&'static str, &'static str)] = &[
    (&"ai", &"爱"),
    (&"ba", &"八"),
    (&"baba", &"爸爸"),
    (&"beizi", &"杯子"),
    (&"beijing", &"北京"),
    (&"ben", &"本"),
    (&"bukeqi", &"不客气"),
    (&"bu", &"不"),
    (&"cai", &"菜"),
    (&"cha", &"茶"),
    (&"chi", &"吃"),
    (&"chuzuche", &"出租车"),
    (&"dadianhua", &"打电话"),
    (&"da", &"大"),
    (&"de", &"的"),
    (&"dian", &"点"),
    (&"diannao", &"电脑"),
    (&"dianshi", &"电视"),
    (&"dianying", &"电影"),
    (&"dongxi", &"东西"),
    (&"dou", &"都"),
    (&"du", &"读"),
    (&"duibuqi", &"对不起"),
    (&"duo", &"多"),
    (&"duoshao", &"多少"),
    (&"erzi", &"儿子"),
    (&"er", &"二"),
    (&"fandian", &"饭店"),
    (&"feiji", &"飞机"),
    (&"fenzhong", &"分钟"),
    (&"gaoxing", &"高兴"),
    (&"ge", &"个"),
    (&"gongzuo", &"工作"),
    (&"gou", &"狗"),
    (&"hanyu", &"汉语"),
    (&"hao", &"好"),
    (&"hao", &"号"),
    (&"he", &"喝"),
    (&"he", &"和"),
    (&"hen", &"很"),
    (&"houmian", &"后面"),
    (&"hui", &"回"),
    (&"hui", &"会"),
    (&"ji", &"几"),
    (&"jia", &"家"),
    (&"jiao", &"叫"),
    (&"jintian", &"今天"),
    (&"jiu", &"九"),
    (&"kai", &"开"),
    (&"kan", &"看"),
    (&"kanjian", &"看见"),
    (&"kuai", &"块"),
    (&"lai", &"来"),
    (&"laoshi", &"老师"),
    (&"le", &"了"),
    (&"leng", &"冷"),
    (&"li", &"里"),
    (&"liu", &"六"),
    (&"mama", &"妈妈"),
    (&"ma", &"吗"),
    (&"mai", &"买"),
    (&"mao", &"猫"),
    (&"meiguanxi", &"没关系"),
    (&"meiyou", &"没有"),
    (&"mifan", &"米饭"),
    (&"mingzi", &"名字"),
    (&"mingtian", &"明天"),
    (&"na", &"哪"),
    (&"nar", &"哪儿"),
    (&"na", &"那"),
    (&"ne", &"呢"),
    (&"neng", &"能"),
    (&"ni", &"你"),
    (&"nian", &"年"),
    (&"nver", &"女儿"),
    (&"pengyou", &"朋友"),
    (&"piaoliang", &"漂亮"),
    (&"pingguo", &"苹果"),
    (&"qi", &"七"),
    (&"qianmian", &"前面"),
    (&"qian", &"钱"),
    (&"qing", &"请"),
    (&"qu", &"去"),
    (&"re", &"热"),
    (&"ren", &"人"),
    (&"renshi", &"认识"),
    (&"san", &"三"),
    (&"shangdian", &"商店"),
    (&"shang", &"上"),
    (&"shangwu", &"上午"),
    (&"shao", &"少"),
    (&"shei", &"谁"),
    (&"shenme", &"什么"),
    (&"shi", &"十"),
    (&"shihou", &"时候"),
    (&"shi", &"是"),
    (&"shu", &"书"),
    (&"shui", &"水"),
    (&"shuiguo", &"水果"),
    (&"shuijiao", &"睡觉"),
    (&"shuo", &"说"),
    (&"si", &"四"),
    (&"sui", &"岁"),
    (&"ta", &"他"),
    (&"ta", &"她"),
    (&"tai", &"太"),
    (&"tianqi", &"天气"),
    (&"ting", &"听"),
    (&"tongxue", &"同学"),
    (&"wei", &"喂"),
    (&"wo", &"我"),
    (&"women", &"我们"),
    (&"wu", &"五"),
    (&"xihuan", &"喜欢"),
    (&"xia", &"下"),
    (&"xiawu", &"下午"),
    (&"xiayu", &"下雨"),
    (&"xiansheng", &"先生"),
    (&"xianzai", &"现在"),
    (&"xiang", &"想"),
    (&"xiao", &"小"),
    (&"xiaojie", &"小姐"),
    (&"xie", &"些"),
    (&"xie", &"写"),
    (&"xiexie", &"谢谢"),
    (&"xingqi", &"星期"),
    (&"xuesheng", &"学生"),
    (&"xuexi", &"学习"),
    (&"xuexiao", &"学校"),
    (&"yi", &"一"),
    (&"yifu", &"衣服"),
    (&"yisheng", &"医生"),
    (&"yiyuan", &"医院"),
    (&"yizi", &"椅子"),
    (&"yidianr", &"一点儿"),
    (&"you", &"有"),
    (&"yue", &"月"),
    (&"zaijian", &"再见"),
    (&"zai", &"在"),
    (&"zenme", &"怎么"),
    (&"zenmeyang", &"怎么样"),
    (&"zhe", &"这"),
    (&"zhongguo", &"中国"),
    (&"zhongwu", &"中午"),
    (&"zhu", &"住"),
    (&"zhuozi", &"桌子"),
    (&"zi", &"字"),
    (&"zuotian", &"昨天"),
    (&"zuo", &"坐"),
    (&"zuo", &"做"),
    (&"dawei", &"大卫"),
    (&"li", &"李"),
    (&"meiguo", &"美国"),
    (&"wang", &"王"),
    (&"fang", &"方"),
    (&"xie", &"谢"),
    (&"peng", &"朋"),
    (&"bushao", &"不少"),
    (&"che", &"车"),
    (&"chifan", &"吃饭"),
    (&"daxue", &"大学"),
    (&"guo", &"国"),
    (&"hanzi", &"汉字"),
    (&"hou", &"后"),
    (&"huilai", &"回来"),
    (&"jinnian", &"今年"),
    (&"mei", &"没"),
    (&"nar", &"那儿"),
    (&"nimen", &"你们"),
    (&"qian", &"前"),
    (&"xiamian", &"下面"),
    (&"xue", &"学"),
    (&"yu", &"雨"),
    (&"zher", &"这儿"),
    (&"zhexie", &"这些"),
    (&"ba", &"吧"),
    (&"bai", &"白"),
    (&"bai", &"百"),
    (&"bangzhu", &"帮助"),
    (&"baozhi", &"报纸"),
    (&"bi", &"比"),
    (&"bie", &"别"),
    (&"binguan", &"宾馆"),
    (&"chang", &"长"),
    (&"changge", &"唱歌"),
    (&"chu", &"出"),
    (&"chuan", &"穿"),
    (&"ci", &"次"),
    (&"cong", &"从"),
    (&"cuo", &"错"),
    (&"dalanqiu", &"打篮球"),
    (&"dajia", &"大家"),
    (&"danshi", &"但是"),
    (&"dao", &"到"),
    (&"de", &"得"),
    (&"deng", &"等"),
    (&"didi", &"弟弟"),
    (&"diyi", &"第一"),
    (&"dong", &"懂"),
    (&"dui", &"对"),
    (&"fangjian", &"房间"),
    (&"feichang", &"非常"),
    (&"fuwuyuan", &"服务员"),
    (&"gao", &"高"),
    (&"gaosu", &"告诉"),
    (&"gege", &"哥哥"),
    (&"gei", &"给"),
    (&"gonggongqiche", &"公共汽车"),
    (&"gongsi", &"公司"),
    (&"gui", &"贵"),
    (&"guo", &"过"),
    (&"hai", &"还"),
    (&"haizi", &"孩子"),
    (&"haochi", &"好吃"),
    (&"hei", &"黑"),
    (&"hong", &"红"),
    (&"huochezhan", &"火车站"),
    (&"jichang", &"机场"),
    (&"jidan", &"鸡蛋"),
    (&"jian", &"件"),
    (&"juede", &"觉得"),
    (&"jiaoshi", &"教室"),
    (&"jiejie", &"姐姐"),
    (&"jieshao", &"介绍"),
    (&"jin", &"进"),
    (&"jin", &"近"),
    (&"jiu", &"就"),
    (&"kafei", &"咖啡"),
    (&"kaishi", &"开始"),
    (&"kaoshi", &"考试"),
    (&"keneng", &"可能"),
    (&"keyi", &"可以"),
    (&"ke", &"课"),
    (&"kuai", &"快"),
    (&"kuaile", &"快乐"),
    (&"lei", &"累"),
    (&"li", &"离"),
    (&"liang", &"两"),
    (&"ling", &"零"),
    (&"lu", &"路"),
    (&"lvyou", &"旅游"),
    (&"mai", &"卖"),
    (&"man", &"慢"),
    (&"mang", &"忙"),
    (&"mei", &"每"),
    (&"meimei", &"妹妹"),
    (&"men", &"门"),
    (&"miantiao", &"面条"),
    (&"nan", &"男"),
    (&"nin", &"您"),
    (&"niunai", &"牛奶"),
    (&"nv", &"女"),
    (&"pangbian", &"旁边"),
    (&"paobu", &"跑步"),
    (&"pianyi", &"便宜"),
    (&"piao", &"票"),
    (&"qizi", &"妻子"),
    (&"qichuang", &"起床"),
    (&"qian", &"千"),
    (&"qianbi", &"铅笔"),
    (&"qing", &"晴"),
    (&"qunian", &"去年"),
    (&"rang", &"让"),
    (&"ri", &"日"),
    (&"shangban", &"上班"),
    (&"shenti", &"身体"),
    (&"shengbing", &"生病"),
    (&"shengri", &"生日"),
    (&"shijian", &"时间"),
    (&"shiqing", &"事情"),
    (&"shoubiao", &"手表"),
    (&"shouji", &"手机"),
    (&"shuohua", &"说话"),
    (&"song", &"送"),
    (&"suiran", &"虽然"),
    (&"suoyi", &"所以"),
    (&"ta", &"它"),
    (&"tizuqiu", &"踢足球"),
    (&"ti", &"题"),
    (&"tiaowu", &"跳舞"),
    (&"wai", &"外"),
    (&"wan", &"完"),
    (&"wan", &"玩"),
    (&"wanr", &"玩儿"),
    (&"wanshang", &"晚上"),
    (&"wang", &"往"),
    (&"weishenme", &"为什么"),
    (&"wen", &"问"),
    (&"wenti", &"问题"),
    (&"xigua", &"西瓜"),
    (&"xiwang", &"希望"),
    (&"xi", &"洗"),
    (&"xiaoshi", &"小时"),
    (&"xiao", &"笑"),
    (&"xin", &"新"),
    (&"xing", &"姓"),
    (&"xiuxi", &"休息"),
    (&"xue", &"雪"),
    (&"yanse", &"颜色"),
    (&"yanjing", &"眼睛"),
    (&"yangrou", &"羊肉"),
    (&"yao", &"药"),
    (&"yao", &"要"),
    (&"ye", &"也"),
    (&"yixia", &"一下"),
    (&"yijing", &"已经"),
    (&"yiqi", &"一起"),
    (&"yisi", &"意思"),
    (&"yinwei", &"因为"),
    (&"yin", &"阴"),
    (&"youyong", &"游泳"),
    (&"youbian", &"右边"),
    (&"yu", &"鱼"),
    (&"yuan", &"远"),
    (&"yundong", &"运动"),
    (&"zai", &"再"),
    (&"zaoshang", &"早上"),
    (&"zhangfu", &"丈夫"),
    (&"zhao", &"找"),
    (&"zhe", &"着"),
    (&"zhen", &"真"),
    (&"zhengzai", &"正在"),
    (&"zhidao", &"知道"),
    (&"zhunbei", &"准备"),
    (&"zou", &"走"),
    (&"zui", &"最"),
    (&"zuobian", &"左边"),
    (&"huahua", &"花花"),
    (&"yang", &"杨"),
    (&"xiaoxiao", &"笑笑"),
    (&"du", &"度"),
    (&"fense", &"粉色"),
    (&"yihou", &"以后"),
    (&"bang", &"帮"),
    (&"bucuo", &"不错"),
    (&"chuyuan", &"出院"),
    (&"fen", &"粉"),
    (&"hongse", &"红色"),
    (&"lukou", &"路口"),
    (&"shou", &"手"),
    (&"waimian", &"外面"),
    (&"xinnian", &"新年"),
    (&"youyisi", &"有意思"),
    (&"ayi", &"阿姨"),
    (&"a", &"啊"),
    (&"ai", &"矮"),
    (&"aihao", &"爱好"),
    (&"anjing", &"安静"),
    (&"ba", &"把"),
    (&"ban", &"班"),
    (&"ban", &"搬"),
    (&"banfa", &"办法"),
    (&"bangongshi", &"办公室"),
    (&"ban", &"半"),
    (&"bangmang", &"帮忙"),
    (&"bao", &"包"),
    (&"bao", &"饱"),
    (&"beifang", &"北方"),
    (&"bei", &"被"),
    (&"bizi", &"鼻子"),
    (&"bijiao", &"比较"),
    (&"bisai", &"比赛"),
    (&"bijiben", &"笔记本"),
    (&"bixu", &"必须"),
    (&"bianhua", &"变化"),
    (&"bieren", &"别人"),
    (&"bingxiang", &"冰箱"),
    (&"budan", &"不但"),
    (&"erqie", &"而且"),
    (&"caidan", &"菜单"),
    (&"canjia", &"参加"),
    (&"cao", &"草"),
    (&"ceng", &"层"),
    (&"cha", &"差"),
    (&"chaoshi", &"超市"),
    (&"chenshan", &"衬衫"),
    (&"chengji", &"成绩"),
    (&"chengshi", &"城市"),
    (&"chidao", &"迟到"),
    (&"chule", &"除了"),
    (&"chuan", &"船"),
    (&"chun", &"春"),
    (&"tian", &"天"),
    (&"cidian", &"词典"),
    (&"congming", &"聪明"),
    (&"dasao", &"打扫"),
    (&"dasuan", &"打算"),
    (&"dai", &"带"),
    (&"danxin", &"担心"),
    (&"dangao", &"蛋糕"),
    (&"dangran", &"当然"),
    (&"de", &"地"),
    (&"deng", &"灯"),
    (&"difang", &"地方"),
    (&"ditie", &"地铁"),
    (&"ditu", &"地图"),
    (&"dianti", &"电梯"),
    (&"dianziyoujian", &"电子邮件"),
    (&"dong", &"东"),
    (&"dong", &"冬"),
    (&"dongwu", &"动物"),
    (&"duan", &"短"),
    (&"duan", &"段"),
    (&"duanlian", &"锻炼"),
    (&"duome", &"多么"),
    (&"e", &"饿"),
    (&"erduo", &"耳朵"),
    (&"fa", &"发"),
    (&"fashao", &"发烧"),
    (&"faxian", &"发现"),
    (&"fangbian", &"方便"),
    (&"fang", &"放"),
    (&"fangxin", &"放心"),
    (&"fen", &"分"),
    (&"fujin", &"附近"),
    (&"fuxi", &"复习"),
    (&"ganjing", &"干净"),
    (&"ganmao", &"感冒"),
    (&"ganxingqu", &"感兴趣"),
    (&"gangcai", &"刚才"),
    (&"gezi", &"个子"),
    (&"genju", &"根据"),
    (&"gen", &"跟"),
    (&"geng", &"更"),
    (&"gongjin", &"公斤"),
    (&"gongyuan", &"公园"),
    (&"gushi", &"故事"),
    (&"guafeng", &"刮风"),
    (&"guan", &"关"),
    (&"guanxi", &"关系"),
    (&"guanxin", &"关心"),
    (&"guanyu", &"关于"),
    (&"guojia", &"国家"),
    (&"guo", &"过"),
    (&"guoqu", &"过去"),
    (&"haishi", &"还是"),
    (&"haipa", &"害怕"),
    (&"heiban", &"黑板"),
    (&"houlai", &"后来"),
    (&"huzhao", &"护照"),
    (&"hua", &"花"),
    (&"hua", &"画"),
    (&"huai", &"坏"),
    (&"huanying", &"欢迎"),
    (&"huan", &"还"),
    (&"huanjing", &"环境"),
    (&"huan", &"换"),
    (&"huida", &"回答"),
    (&"huiyi", &"会议"),
    (&"huozhe", &"或者"),
    (&"jihu", &"几乎"),
    (&"jihui", &"机会"),
    (&"ji", &"极"),
    (&"jide", &"记得"),
    (&"jijie", &"季节"),
    (&"jiancha", &"检查"),
    (&"jiandan", &"简单"),
    (&"jianmian", &"见面"),
    (&"jiankang", &"健康"),
    (&"jiang", &"讲"),
    (&"jiao", &"教"),
    (&"jiao", &"角"),
    (&"jiao", &"脚"),
    (&"jie", &"接"),
    (&"jidao", &"街道"),
    (&"jiemu", &"节目"),
    (&"jieri", &"节日"),
    (&"jiehun", &"结婚"),
    (&"jieshu", &"结束"),
    (&"jiejue", &"解决"),
    (&"jie", &"借"),
    (&"jingchang", &"经常"),
    (&"jingguo", &"经过"),
    (&"jingli", &"经理"),
    (&"jiu", &"久"),
    (&"jiu", &"旧"),
    (&"juzi", &"句子"),
    (&"jueding", &"决定"),
    (&"keai", &"可爱"),
    (&"ke", &"渴"),
    (&"ke", &"刻"),
    (&"keren", &"客人"),
    (&"kongtiao", &"空调"),
    (&"kou", &"口"),
    (&"ku", &"哭"),
    (&"kuzi", &"裤子"),
    (&"kuaizi", &"筷子"),
    (&"lan", &"蓝"),
    (&"lao", &"老"),
    (&"likai", &"离开"),
    (&"liwu", &"礼物"),
    (&"lishi", &"历史"),
    (&"lian", &"脸"),
    (&"lianxi", &"练习"),
    (&"liang", &"辆"),
    (&"liaotian", &"聊天"),
    (&"liaotianr", &"聊天儿"),
    (&"liaojie", &"了解"),
    (&"linju", &"邻居"),
    (&"liuxue", &"留学"),
    (&"lou", &"楼"),
    (&"lv", &"绿"),
    (&"ma", &"马"),
    (&"mashang", &"马上"),
    (&"manyi", &"满意"),
    (&"maozi", &"帽子"),
    (&"mi", &"米"),
    (&"mianbao", &"面包"),
    (&"mingbai", &"明白"),
    (&"na", &"拿"),
    (&"nainai", &"奶奶"),
    (&"nan", &"南"),
    (&"nan", &"难"),
    (&"nanguo", &"难过"),
    (&"nianji", &"年级"),
    (&"nianqing", &"年轻"),
    (&"niao", &"鸟"),
    (&"nuli", &"努力"),
    (&"pashan", &"爬山"),
    (&"panzi", &"盘子"),
    (&"pang", &"胖"),
    (&"pixie", &"皮鞋"),
    (&"pijiu", &"啤酒"),
    (&"pingzi", &"瓶子"),
    (&"qishi", &"其实"),
    (&"qita", &"其他"),
    (&"qiguai", &"奇怪"),
    (&"qi", &"骑"),
    (&"qifei", &"起飞"),
    (&"qilai", &"起来"),
    (&"qingchu", &"清楚"),
    (&"qingjia", &"请假"),
    (&"qiu", &"秋"),
    (&"qunzi", &"裙子"),
    (&"ranhou", &"然后"),
    (&"reqing", &"热情"),
    (&"renwei", &"认为"),
    (&"renzhen", &"认真"),
    (&"rongyi", &"容易"),
    (&"ruguo", &"如果"),
    (&"san", &"伞"),
    (&"shangwang", &"上网"),
    (&"shengqi", &"生气"),
    (&"shengyin", &"声音"),
    (&"shijie", &"世界"),
    (&"shi", &"试"),
    (&"shou", &"瘦"),
    (&"shushu", &"叔叔"),
    (&"shufu", &"舒服"),
    (&"shu", &"树"),
    (&"shuxue", &"数学"),
    (&"shuaya", &"刷牙"),
    (&"shuang", &"双"),
    (&"shuiping", &"水平"),
    (&"siji", &"司机"),
    (&"taiyang", &"太阳"),
    (&"tebie", &"特别"),
    (&"teng", &"疼"),
    (&"tigao", &"提高"),
    (&"tiyu", &"体育"),
    (&"tian", &"甜"),
    (&"tiao", &"条"),
    (&"tongshi", &"同事"),
    (&"tongyi", &"同意"),
    (&"toufa", &"头发"),
    (&"turan", &"突然"),
    (&"tushuguan", &"图书馆"),
    (&"tui", &"腿"),
    (&"wancheng", &"完成"),
    (&"wan", &"碗"),
    (&"wan", &"万"),
    (&"wangji", &"忘记"),
    (&"wei", &"为"),
    (&"weile", &"为了"),
    (&"wei", &"位"),
    (&"wenhua", &"文化"),
    (&"xi", &"西"),
    (&"xiguan", &"习惯"),
    (&"xishoujian", &"洗手间"),
    (&"xizao", &"洗澡"),
    (&"xia", &"夏"),
    (&"xian", &"先"),
    (&"xiangxin", &"相信"),
    (&"xiangjiao", &"香蕉"),
    (&"xiang", &"向"),
    (&"xiang", &"像"),
    (&"xiaoxin", &"小心"),
    (&"xiaozhang", &"校长"),
    (&"xinwen", &"新闻"),
    (&"xinxian", &"新鲜"),
    (&"xinyongka", &"信用卡"),
    (&"xinglixiang", &"行李箱"),
    (&"xiongmao", &"熊猫"),
    (&"xuyao", &"需要"),
    (&"xuanze", &"选择"),
    (&"yaoqiu", &"要求"),
    (&"yeye", &"爷爷"),
    (&"yiding", &"一定"),
    (&"yigong", &"一共"),
    (&"yihuir", &"一会儿"),
    (&"yihuier", &"一会儿"),
    (&"yiyang", &"一样"),
    (&"yiqian", &"以前"),
    (&"yiban", &"一般"),
    (&"yibian", &"一边"),
    (&"yizhi", &"一直"),
    (&"yinyue", &"音乐"),
    (&"yinhang", &"银行"),
    (&"yinliao", &"饮料"),
    (&"yinggai", &"应该"),
    (&"yingxiang", &"影响"),
    (&"yong", &"用"),
    (&"youxi", &"游戏"),
    (&"youming", &"有名"),
    (&"you", &"又"),
    (&"yudao", &"遇到"),
    (&"yuan", &"元"),
    (&"yuanyi", &"愿意"),
    (&"yueliang", &"月亮"),
    (&"yue", &"越"),
    (&"zhan", &"站"),
    (&"zhang", &"张"),
    (&"zhang", &"长"),
    (&"zhaoji", &"着急"),
    (&"zhaogu", &"照顾"),
    (&"zhaopian", &"照片"),
    (&"zhaoxiangji", &"照相机"),
    (&"zhi", &"只"),
    (&"zhiyou", &"只有"),
    (&"cai", &"才"),
    (&"zhongjian", &"中间"),
    (&"zhongyu", &"终于"),
    (&"zhong", &"种"),
    (&"zhongyao", &"重要"),
    (&"zhoumo", &"周末"),
    (&"zhuyao", &"主要"),
    (&"zhuyi", &"注意"),
    (&"ziji", &"自己"),
    (&"zixingche", &"自行车"),
    (&"zongshi", &"总是"),
    (&"zui", &"嘴"),
    (&"zuihou", &"最后"),
    (&"zuijin", &"最近"),
    (&"zuoye", &"作业"),
    (&"huanghe", &"黄河"),
    (&"zhongwen", &"中文"),
    (&"shan", &"山"),
    (&"huang", &"黄"),
    (&"he", &"河"),
    (&"jing", &"静"),
    (&"ke", &"可"),
    (&"li", &"丽"),
    (&"ming", &"明"),
    (&"zhou", &"周"),
    (&"kele", &"可乐"),
    (&"mishu", &"秘书"),
    (&"shuizhao", &"睡着"),
    (&"banshi", &"办事"),
    (&"bian", &"变"),
    (&"chunjie", &"春节"),
    (&"da", &"打"),
    (&"daoshihou", &"到时候"),
    (&"fangzi", &"房子"),
    (&"gewu", &"歌舞"),
    (&"hongjiu", &"红酒"),
    (&"jiu", &"酒"),
    (&"ju", &"句"),
    (&"meitian", &"每天"),
    (&"nali", &"哪里"),
    (&"nvhair", &"女孩儿"),
    (&"nvhai", &"女孩"),
    (&"qianbao", &"钱包"),
    (&"renming", &"人名"),
    (&"ren", &"认"),
    (&"tingshuo", &"听说"),
    (&"waidi", &"外地"),
    (&"xianhua", &"鲜花"),
    (&"xianggua", &"香瓜"),
    (&"yibanlaishuo", &"一般来说"),
    (&"yinyuehui", &"音乐会"),
    (&"youdianr", &"有点儿"),
    (&"youdian", &"有点"),
    (&"zao", &"早"),
    (&"zenmeban", &"怎么办"),
    (&"zhongqiujie", &"中秋节"),
    (&"aiqing", &"爱情"),
    (&"anpai", &"安排"),
    (&"anshi", &"按时"),
    (&"anzhao", &"按照"),
    (&"baifenzhi", &"百分之"),
    (&"baozheng", &"保证"),
    (&"bei", &"倍"),
    (&"benlai", &"本来"),
    (&"biru", &"比如"),
    (&"biye", &"毕业"),
    (&"biaozhun", &"标准"),
    (&"binggan", &"饼干"),
    (&"budebu", &"不得不"),
    (&"buguan", &"不管"),
    (&"buguo", &"不过"),
    (&"bujin", &"不仅"),
    (&"ca", &"擦"),
    (&"cailiao", &"材料"),
    (&"chabuduo", &"差不多"),
    (&"chang", &"尝"),
    (&"chaoguo", &"超过"),
    (&"chenggong", &"成功"),
    (&"chengwei", &"成为"),
    (&"chengshi", &"诚实"),
    (&"chongxin", &"重新"),
    (&"chouyan", &"抽烟"),
    (&"chuxian", &"出现"),
    (&"chuanghu", &"窗户"),
    (&"conglai", &"从来"),
    (&"daan", &"答案"),
    (&"darao", &"打扰"),
    (&"dazhe", &"打折"),
    (&"dashiguan", &"大使馆"),
    (&"daifu", &"大夫"),
    (&"dang", &"当"),
    (&"dangshi", &"当时"),
    (&"daochu", &"到处"),
    (&"dei", &"得"),
    (&"deng", &"等"),
    (&"di", &"低"),
    (&"diaocha", &"调查"),
    (&"diao", &"掉"),
    (&"dongzuo", &"动作"),
    (&"duche", &"堵车"),
    (&"duzi", &"肚子"),
    (&"duanxin", &"短信"),
    (&"er", &"而"),
    (&"fasheng", &"发生"),
    (&"fazhan", &"发展"),
    (&"falv", &"法律"),
    (&"fanyi", &"翻译"),
    (&"fannao", &"烦恼"),
    (&"fandui", &"反对"),
    (&"fangfa", &"方法"),
    (&"fangmian", &"方面"),
    (&"fangxiang", &"方向"),
    (&"fangqi", &"放弃"),
    (&"fangsong", &"放松"),
    (&"fen", &"份"),
    (&"fengfu", &"丰富"),
    (&"fuhe", &"符合"),
    (&"fuze", &"负责"),
    (&"fu", &"富"),
    (&"gaibian", &"改变"),
    (&"gandong", &"感动"),
    (&"ganjue", &"感觉"),
    (&"ganqing", &"感情"),
    (&"ganxie", &"感谢"),
    (&"gang", &"刚"),
    (&"ge", &"各"),
    (&"gongzi", &"工资"),
    (&"gongtong", &"共同"),
    (&"gouwu", &"购物"),
    (&"gou", &"够"),
    (&"guji", &"估计"),
    (&"guke", &"顾客"),
    (&"guanjian", &"关键"),
    (&"guang", &"光"),
    (&"guanggao", &"广告"),
    (&"guang", &"逛"),
    (&"guoji", &"国际"),
    (&"guozhi", &"果汁"),
    (&"guocheng", &"过程"),
    (&"han", &"汗"),
    (&"haochu", &"好处"),
    (&"haoxiang", &"好像"),
    (&"houhui", &"后悔"),
    (&"huxiang", &"互相"),
    (&"huiyi", &"回忆"),
    (&"huodong", &"活动"),
    (&"huode", &"获得"),
    (&"jiji", &"积极"),
    (&"jilei", &"积累"),
    (&"jishi", &"及时"),
    (&"jishi", &"即使"),
    (&"jihua", &"计划"),
    (&"ji", &"寄"),
    (&"jiaban", &"加班"),
    (&"jiaju", &"家具"),
    (&"jiage", &"价格"),
    (&"jianchi", &"坚持"),
    (&"jianfei", &"减肥"),
    (&"jianyi", &"建议"),
    (&"jianglai", &"将来"),
    (&"jiangjin", &"奖金"),
    (&"jiangdi", &"降低"),
    (&"jiao", &"交"),
    (&"jiaoliu", &"交流"),
    (&"jiaoshou", &"教授"),
    (&"jieshou", &"接受"),
    (&"jieguo", &"结果"),
    (&"jinguan", &"尽管"),
    (&"jinzhang", &"紧张"),
    (&"jingji", &"经济"),
    (&"jingli", &"经历"),
    (&"jingyan", &"经验"),
    (&"jingse", &"景色"),
    (&"jingran", &"竟然"),
    (&"jingzi", &"镜子"),
    (&"juban", &"举办"),
    (&"juxing", &"举行"),
    (&"juli", &"距离"),
    (&"juhui", &"聚会"),
    (&"kaiwanxiao", &"开玩笑"),
    (&"kaolv", &"考虑"),
    (&"kexue", &"科学"),
    (&"kesou", &"咳嗽"),
    (&"keshi", &"可是"),
    (&"kending", &"肯定"),
    (&"kongqi", &"空气"),
    (&"kongr", &"空儿"),
    (&"kun", &"困"),
    (&"kunnan", &"困难"),
    (&"la", &"拉"),
    (&"laibuji", &"来不及"),
    (&"langfei", &"浪费"),
    (&"langman", &"浪漫"),
    (&"libaitian", &"礼拜天"),
    (&"lijie", &"理解"),
    (&"lixiang", &"理想"),
    (&"liru", &"例如"),
    (&"lia", &"俩"),
    (&"lianxi", &"联系"),
    (&"lingwai", &"另外"),
    (&"liu", &"留"),
    (&"liuxing", &"流行"),
    (&"lvshi", &"律师"),
    (&"luan", &"乱"),
    (&"mafan", &"麻烦"),
    (&"man", &"满"),
    (&"mianfei", &"免费"),
    (&"muqin", &"母亲"),
    (&"naixin", &"耐心"),
    (&"nandao", &"难道"),
    (&"nei", &"内"),
    (&"nengli", &"能力"),
    (&"nianling", &"年龄"),
    (&"panduan", &"判断"),
    (&"pei", &"陪"),
    (&"pifu", &"皮肤"),
    (&"piqi", &"脾气"),
    (&"pian", &"篇"),
    (&"pingshi", &"平时"),
    (&"putao", &"葡萄"),
    (&"qici", &"其次"),
    (&"qizhong", &"其中"),
    (&"qihou", &"气候"),
    (&"qiaokeli", &"巧克力"),
    (&"qinqi", &"亲戚"),
    (&"qing", &"轻"),
    (&"qingsong", &"轻松"),
    (&"qingkuang", &"情况"),
    (&"qiong", &"穷"),
    (&"qubie", &"区别"),
    (&"qu", &"取"),
    (&"quedian", &"缺点"),
    (&"queshao", &"缺少"),
    (&"que", &"却"),
    (&"queshi", &"确实"),
    (&"renhe", &"任何"),
    (&"sanbu", &"散步"),
    (&"shafa", &"沙发"),
    (&"shangxin", &"伤心"),
    (&"shen", &"深"),
    (&"shenzhi", &"甚至"),
    (&"shenghuo", &"生活"),
    (&"shengming", &"生命"),
    (&"shengyi", &"生意"),
    (&"shibai", &"失败"),
    (&"shifu", &"师傅"),
    (&"shiji", &"实际"),
    (&"shizai", &"实在"),
    (&"shi", &"使"),
    (&"shihe", &"适合"),
    (&"shiying", &"适应"),
    (&"shouru", &"收入"),
    (&"shouxian", &"首先"),
    (&"shoudao", &"受到"),
    (&"shouhuoyuan", &"售货员"),
    (&"shuxi", &"熟悉"),
    (&"shuzi", &"数字"),
    (&"shuai", &"帅"),
    (&"shunbian", &"顺便"),
    (&"shunli", &"顺利"),
    (&"shuoming", &"说明"),
    (&"shuoshi", &"硕士"),
    (&"suibian", &"随便"),
    (&"suoyou", &"所有"),
    (&"tai", &"台"),
    (&"taidu", &"态度"),
    (&"tan", &"谈"),
    (&"tang", &"糖"),
    (&"tang", &"躺"),
    (&"taoyan", &"讨厌"),
    (&"tedian", &"特点"),
    (&"ti", &"提"),
    (&"tigong", &"提供"),
    (&"tiqian", &"提前"),
    (&"tixing", &"提醒"),
    (&"tiaojian", &"条件"),
    (&"ting", &"挺"),
    (&"tongguo", &"通过"),
    (&"tongzhi", &"通知"),
    (&"wazi", &"袜子"),
    (&"wanquan", &"完全"),
    (&"wangqiu", &"网球"),
    (&"wangwang", &"往往"),
    (&"weidao", &"味道"),
    (&"wuliao", &"无聊"),
    (&"xihongshi", &"西红柿"),
    (&"xiyin", &"吸引"),
    (&"xianjin", &"现金"),
    (&"xianmu", &"羡慕"),
    (&"xiangpi", &"橡皮"),
    (&"xiaoxi", &"消息"),
    (&"xiaoshuo", &"小说"),
    (&"xiaoguo", &"效果"),
    (&"xinqing", &"心情"),
    (&"xinku", &"辛苦"),
    (&"xinxin", &"信心"),
    (&"xingfen", &"兴奋"),
    (&"xingfu", &"幸福"),
    (&"xingge", &"性格"),
    (&"xiuli", &"修理"),
    (&"xuduo", &"许多"),
    (&"yali", &"压力"),
    (&"yanzhong", &"严重"),
    (&"yanjiu", &"研究"),
    (&"yangguang", &"阳光"),
    (&"yangzi", &"样子"),
    (&"yaoqing", &"邀请"),
    (&"yaoshi", &"要是"),
    (&"yiqie", &"一切"),
    (&"yiwei", &"以为"),
    (&"yishu", &"艺术"),
    (&"yinci", &"因此"),
    (&"yinxiang", &"印象"),
    (&"ying", &"赢"),
    (&"yingpin", &"应聘"),
    (&"yongyuan", &"永远"),
    (&"yonggan", &"勇敢"),
    (&"youdian", &"优点"),
    (&"youxiu", &"优秀"),
    (&"youmo", &"幽默"),
    (&"youqi", &"尤其"),
    (&"youyu", &"由于"),
    (&"youyi", &"友谊"),
    (&"yukuai", &"愉快"),
    (&"yu", &"与"),
    (&"yuanlai", &"原来"),
    (&"yuanyin", &"原因"),
    (&"yuehui", &"约会"),
    (&"zanmen", &"咱们"),
    (&"zanshi", &"暂时"),
    (&"zeren", &"责任"),
    (&"zhaopin", &"招聘"),
    (&"zhenzheng", &"真正"),
    (&"zhenghao", &"正好"),
    (&"zhengque", &"正确"),
    (&"zhengshi", &"正式"),
    (&"zhengming", &"证明"),
    (&"zhichi", &"支持"),
    (&"zhishi", &"知识"),
    (&"zhide", &"值得"),
    (&"zhiye", &"职业"),
    (&"zhiwu", &"植物"),
    (&"zhiyao", &"只要"),
    (&"zhi", &"指"),
    (&"zhishao", &"至少"),
    (&"zhiliang", &"质量"),
    (&"zhouwei", &"周围"),
    (&"zhuyi", &"主意"),
    (&"zhuanmen", &"专门"),
    (&"zhuanye", &"专业"),
    (&"zhuan", &"赚"),
    (&"zhunshi", &"准时"),
    (&"ziran", &"自然"),
    (&"zongjie", &"总结"),
    (&"zuihao", &"最好"),
    (&"zuojia", &"作家"),
    (&"anquan", &"安全"),
    (&"bang", &"棒"),
    (&"baozi", &"包子"),
    (&"baohu", &"保护"),
    (&"baoming", &"报名"),
    (&"bao", &"抱"),
    (&"baoqian", &"抱歉"),
    (&"ben", &"笨"),
    (&"bian", &"遍"),
    (&"biaoge", &"表格"),
    (&"biaoshi", &"表示"),
    (&"biaoyan", &"表演"),
    (&"biaoyang", &"表扬"),
    (&"bingqie", &"并且"),
    (&"boshi", &"博士"),
    (&"bufen", &"部分"),
    (&"cai", &"猜"),
    (&"canguan", &"参观"),
    (&"canting", &"餐厅"),
    (&"cesuo", &"厕所"),
    (&"chang", &"场"),
    (&"chengzuo", &"乘坐"),
    (&"chijing", &"吃惊"),
    (&"chuchai", &"出差"),
    (&"chufa", &"出发"),
    (&"chusheng", &"出生"),
    (&"chufang", &"厨房"),
    (&"chuanzhen", &"传真"),
    (&"ciyu", &"词语"),
    (&"cuxin", &"粗心"),
    (&"cun", &"存"),
    (&"cuowu", &"错误"),
    (&"daban", &"打扮"),
    (&"dayin", &"打印"),
    (&"dazhaohu", &"打招呼"),
    (&"dazhen", &"打针"),
    (&"dagai", &"大概"),
    (&"dayue", &"大约"),
    (&"dai", &"戴"),
    (&"dao", &"刀"),
    (&"daoyou", &"导游"),
    (&"daodi", &"到底"),
    (&"dao", &"倒"),
    (&"daoqian", &"道歉"),
    (&"deyi", &"得意"),
    (&"dengjipai", &"登机牌"),
    (&"di", &"底"),
    (&"didian", &"地点"),
    (&"diqiu", &"地球"),
    (&"dizhi", &"地址"),
    (&"diu", &"丢"),
    (&"duihua", &"对话"),
    (&"duimian", &"对面"),
    (&"duiyu", &"对于"),
    (&"ertong", &"儿童"),
    (&"fangdong", &"房东"),
    (&"fangshujia", &"放暑假"),
    (&"fouze", &"否则"),
    (&"fuqin", &"父亲"),
    (&"fukuan", &"付款"),
    (&"fuyin", &"复印"),
    (&"fuza", &"复杂"),
    (&"ganbei", &"干杯"),
    (&"gan", &"赶"),
    (&"gan", &"敢"),
    (&"gan", &"干"),
    (&"gaosugonglu", &"高速公路"),
    (&"gebo", &"胳膊"),
    (&"gongli", &"公里"),
    (&"gongfu", &"功夫"),
    (&"guli", &"鼓励"),
    (&"guyi", &"故意"),
    (&"gua", &"挂"),
    (&"guanzhong", &"观众"),
    (&"guanli", &"管理"),
    (&"guangbo", &"广播"),
    (&"guiding", &"规定"),
    (&"guoji", &"国籍"),
    (&"haiyang", &"海洋"),
    (&"haixiu", &"害羞"),
    (&"hanjia", &"寒假"),
    (&"hangban", &"航班"),
    (&"haoma", &"号码"),
    (&"hege", &"合格"),
    (&"heshi", &"合适"),
    (&"hezi", &"盒子"),
    (&"hou", &"厚"),
    (&"hulianwang", &"互联网"),
    (&"hushi", &"护士"),
    (&"huaiyi", &"怀疑"),
    (&"huopo", &"活泼"),
    (&"huo", &"火"),
    (&"jichu", &"基础"),
    (&"jidong", &"激动"),
    (&"jizhe", &"记者"),
    (&"jishu", &"技术"),
    (&"jiran", &"既然"),
    (&"jixu", &"继续"),
    (&"jiayouzhan", &"加油站"),
    (&"jia", &"假"),
    (&"jianshao", &"减少"),
    (&"jiangluo", &"降落"),
    (&"jiaotong", &"交通"),
    (&"jiaoqu", &"郊区"),
    (&"jiaoao", &"骄傲"),
    (&"jiaozi", &"饺子"),
    (&"jiaoyu", &"教育"),
    (&"jiezhe", &"接着"),
    (&"jie", &"节"),
    (&"jieyue", &"节约"),
    (&"jieshi", &"解释"),
    (&"jinxing", &"进行"),
    (&"jinzhi", &"禁止"),
    (&"jingju", &"京剧"),
    (&"jingcai", &"精彩"),
    (&"jingcha", &"警察"),
    (&"jingzheng", &"竞争"),
    (&"jiujing", &"究竟"),
    (&"ju", &"举"),
    (&"jujue", &"拒绝"),
    (&"kaixin", &"开心"),
    (&"kanfa", &"看法"),
    (&"kaoya", &"烤鸭"),
    (&"ke", &"棵"),
    (&"kelian", &"可怜"),
    (&"kexi", &"可惜"),
    (&"keting", &"客厅"),
    (&"kong", &"空"),
    (&"kongpa", &"恐怕"),
    (&"ku", &"苦"),
    (&"kuangquanshui", &"矿泉水"),
    (&"lajitong", &"垃圾桶"),
    (&"la", &"辣"),
    (&"laideji", &"来得及"),
    (&"laizi", &"来自"),
    (&"lan", &"懒"),
    (&"laohu", &"老虎"),
    (&"lengjing", &"冷静"),
    (&"limao", &"礼貌"),
    (&"lifa", &"理发"),
    (&"liqi", &"力气"),
    (&"lihai", &"厉害"),
    (&"lian", &"连"),
    (&"liangkuai", &"凉快"),
    (&"lingqian", &"零钱"),
    (&"liuli", &"流利"),
    (&"lvxing", &"旅行"),
    (&"mahu", &"马虎"),
    (&"mao", &"毛"),
    (&"maojin", &"毛巾"),
    (&"meili", &"美丽"),
    (&"meng", &"梦"),
    (&"milu", &"迷路"),
    (&"mima", &"密码"),
    (&"miao", &"秒"),
    (&"minzu", &"民族"),
    (&"mudi", &"目的"),
    (&"nanshou", &"难受"),
    (&"neirong", &"内容"),
    (&"nong", &"弄"),
    (&"nuanhuo", &"暖和"),
    (&"ouer", &"偶尔"),
    (&"paidui", &"排队"),
    (&"pailie", &"排列"),
    (&"piping", &"批评"),
    (&"pian", &"骗"),
    (&"pingpangqiu", &"乒乓球"),
    (&"po", &"破"),
    (&"pubian", &"普遍"),
    (&"putonghua", &"普通话"),
    (&"qianwan", &"千万"),
    (&"qianzheng", &"签证"),
    (&"qiao", &"敲"),
    (&"qiao", &"桥"),
    (&"quanbu", &"全部"),
    (&"raner", &"然而"),
    (&"renao", &"热闹"),
    (&"renwu", &"任务"),
    (&"reng", &"扔"),
    (&"rengran", &"仍然"),
    (&"riji", &"日记"),
    (&"rukou", &"入口"),
    (&"senlin", &"森林"),
    (&"shangliang", &"商量"),
    (&"shaowei", &"稍微"),
    (&"shao", &"勺"),
    (&"shaozi", &"勺子"),
    (&"shehui", &"社会"),
    (&"shenqing", &"申请"),
    (&"sheng", &"省"),
    (&"sheng", &"省"),
    (&"sheng", &"剩"),
    (&"shiwang", &"失望"),
    (&"shifen", &"十分"),
    (&"shiyong", &"使用"),
    (&"shiji", &"世纪"),
    (&"shifou", &"是否"),
    (&"shou", &"收"),
    (&"shoushi", &"收拾"),
    (&"shoudu", &"首都"),
    (&"shoubuliao", &"受不了"),
    (&"shu", &"输"),
    (&"shuliang", &"数量"),
    (&"shunxu", &"顺序"),
    (&"si", &"死"),
    (&"sudu", &"速度"),
    (&"suliaodai", &"塑料袋"),
    (&"suan", &"酸"),
    (&"suizhe", &"随着"),
    (&"sunzi", &"孙子"),
    (&"tai", &"抬"),
    (&"tangangqin", &"弹钢琴"),
    (&"tang", &"汤"),
    (&"tang", &"趟"),
    (&"taolun", &"讨论"),
    (&"tiankong", &"填空"),
    (&"ting", &"停"),
    (&"tongqing", &"同情"),
    (&"tongshi", &"同时"),
    (&"tui", &"推"),
    (&"tuichi", &"推迟"),
    (&"tuo", &"脱"),
    (&"wangzhan", &"网站"),
    (&"weixian", &"危险"),
    (&"weishengjian", &"卫生间"),
    (&"wendu", &"温度"),
    (&"wenzhang", &"文章"),
    (&"wuran", &"污染"),
    (&"wu", &"无"),
    (&"wufa", &"无法"),
    (&"wulun", &"无论"),
    (&"wuhui", &"误会"),
    (&"xian", &"咸"),
    (&"xiangfan", &"相反"),
    (&"xiangtong", &"相同"),
    (&"xiang", &"香"),
    (&"xiangxi", &"详细"),
    (&"xiang", &"响"),
    (&"xiaochi", &"小吃"),
    (&"xiaohuozi", &"小伙子"),
    (&"xiaohua", &"笑话"),
    (&"xinfeng", &"信封"),
    (&"xinxi", &"信息"),
    (&"xing", &"行"),
    (&"xing", &"醒"),
    (&"xingbie", &"性别"),
    (&"xueqi", &"学期"),
    (&"yagao", &"牙膏"),
    (&"ya", &"呀"),
    (&"yange", &"严格"),
    (&"yan", &"盐"),
    (&"yanjing", &"眼镜"),
    (&"yanchu", &"演出"),
    (&"yanyuan", &"演员"),
    (&"yangcheng", &"养成"),
    (&"yaoshi", &"钥匙"),
    (&"yexu", &"也许"),
    (&"yezi", &"叶子"),
    (&"ye", &"页"),
    (&"yi", &"以"),
    (&"yijian", &"意见"),
    (&"yinqi", &"引起"),
    (&"you", &"由"),
    (&"youju", &"邮局"),
    (&"youhao", &"友好"),
    (&"youqu", &"有趣"),
    (&"yushi", &"于是"),
    (&"yumaoqiu", &"羽毛球"),
    (&"yufa", &"语法"),
    (&"yuyan", &"语言"),
    (&"yuxi", &"预习"),
    (&"yuanliang", &"原谅"),
    (&"yuedu", &"阅读"),
    (&"yun", &"云"),
    (&"yunxu", &"允许"),
    (&"zazhi", &"杂志"),
    (&"zang", &"脏"),
    (&"zengjia", &"增加"),
    (&"zhanxian", &"占线"),
    (&"zhao", &"照"),
    (&"zhengli", &"整理"),
    (&"zhengchang", &"正常"),
    (&"zhi", &"之"),
    (&"zhijie", &"直接"),
    (&"zhihao", &"只好"),
    (&"zhidai", &"纸袋"),
    (&"zhong", &"重"),
    (&"zhongdian", &"重点"),
    (&"zhongshi", &"重视"),
    (&"zhuhe", &"祝贺"),
    (&"zhuming", &"著名"),
    (&"zhuan", &"转"),
    (&"zhunque", &"准确"),
    (&"zixi", &"仔细"),
    (&"zixin", &"自信"),
    (&"zu", &"租"),
    (&"zunzhong", &"尊重"),
    (&"zuoyou", &"左右"),
    (&"zuoyong", &"作用"),
    (&"zuozhe", &"作者"),
    (&"zuo", &"座"),
    (&"zuowei", &"座位"),
    (&"changcheng", &"长城"),
    (&"changjiang", &"长江"),
    (&"yazhou", &"亚洲"),
    (&"aidisheng", &"爱迪生"),
    (&"lin", &"林"),
    (&"make", &"马克"),
    (&"shanghai", &"上海"),
    (&"sunyue", &"孙月"),
    (&"xiaoyu", &"小雨"),
    (&"bing", &"并"),
    (&"huiyuanka", &"会员卡"),
    (&"ji", &"即"),
    (&"jingshen", &"精神"),
    (&"liang", &"亮"),
    (&"liuxie", &"流血"),
    (&"miandui", &"面对"),
    (&"xingxing", &"星星"),
    (&"xhileng", &"制冷"),
    (&"an", &"按"),
    (&"bao", &"保"),
    (&"bishi", &"笔试"),
    (&"butong", &"不同"),
    (&"can", &"餐"),
    (&"changqi", &"长期"),
    (&"cheng", &"成"),
    (&"chu", &"处"),
    (&"chuang", &"窗"),
    (&"dedao", &"得到"),
    (&"du", &"堵"),
    (&"fumu", &"父母"),
    (&"gandao", &"感到"),
    (&"gou", &"购"),
    (&"goumai", &"购买"),
    (&"huo", &"货"),
    (&"jia", &"加"),
    (&"jiaqian", &"价钱"),
    (&"jiang", &"奖"),
    (&"jie", &"街"),
    (&"mei", &"美"),
    (&"mianshi", &"面试"),
    (&"nvxing", &"女性"),
    (&"putong", &"普通"),
    (&"shangchang", &"商场"),
    (&"shenbian", &"身边"),
    (&"tiyuguan", &"体育馆"),
    (&"xiaopengyou", &"小朋友"),
    (&"xiaoyuan", &"校园"),
    (&"xinxiangan", &"新鲜感"),
    (&"youguan", &"有关"),
    (&"zan", &"咱"),
    (&"zhe", &"折"),
    (&"zhi", &"纸"),
    (&"zhu", &"祝"),
    (&"zuoke", &"做客"),
    (&"anna", &"安娜"),
    (&"changjiangdaqiao", &"长江大桥"),
    (&"guangdongsheng", &"广东省"),
    (&"liuyiertongjie", &"六一儿童节"),
    (&"shoudujichang", &"首都机场"),
    (&"xiangshan", &"香山"),
    (&"chao", &"吵"),
    (&"dadao", &"达到"),
    (&"daibiao", &"代表"),
    (&"fangshi", &"方式"),
    (&"guai", &"怪"),
    (&"meirenyu", &"美人鱼"),
    (&"naozhong", &"闹钟"),
    (&"shibangongbei", &"事半功倍"),
    (&"wudao", &"舞蹈"),
    (&"zhua", &"抓"),
    (&"biji", &"笔记"),
    (&"biao", &"表"),
    (&"bu", &"部"),
    (&"chunyou", &"春游"),
    (&"dai", &"袋"),
    (&"daizi", &"袋子"),
    (&"fengjing", &"风景"),
    (&"gai", &"改"),
    (&"guanzhu", &"关注"),
    (&"hai", &"海"),
    (&"huanbao", &"环保"),
    (&"jile", &"极了"),
    (&"jiayou", &"加油"),
    (&"jian", &"减"),
    (&"jianqing", &"减轻"),
    (&"keji", &"科技"),
    (&"laji", &"垃圾"),
    (&"lifadian", &"理发店"),
    (&"lizi", &"例子"),
    (&"liangcha", &"凉茶"),
    (&"ling", &"另"),
    (&"meihao", &"美好"),
    (&"nuan", &"暖"),
    (&"qite", &"奇特"),
    (&"qiwen", &"气温"),
    (&"quan", &"全"),
    (&"shou", &"受"),
    (&"shu", &"数"),
    (&"tian", &"填"),
    (&"tongyang", &"同样"),
    (&"xiaoqu", &"小区"),
    (&"xin", &"信"),
    (&"xingqu", &"兴趣"),
    (&"yashua", &"牙刷"),
    (&"yang", &"养"),
    (&"youxiao", &"有效"),
    (&"youxian", &"有限"),
    (&"yue", &"约"),
    (&"zeng", &"增"),
    (&"zengzhang", &"增长"),
];
